signature-crate/Cargo.toml
signature-crate/src/error.rs
signature-crate/src/lib.rs
signature-crate/src/prelude.rs
signature-crate/src/signature.rs

Adds a `Signature` trait which serialized signature types implement.
Adds an initial `Error` type to be returned from `Signature::from_bytes` in the event the signature is not valid.

Initial Signature trait and Error enum

---

.travis.yml
signature-crate/src/lib.rs

Some improvements in response to https://github.com/RustCrypto/signatures/pull/2#pullrequestreview-174880373
Doesn't quite do as an elaborate `no_std` check as the linked example there, however this is at least an improvement over not checking those targets whatsoever.

.travis.yml: Check rustfmt, clippy, docs build, WASM + no_std target builds

---

README.md

Adds an initial description, inspired by the content in other projects.
Adds initial license information (Apache 2.0 + MIT)

README.md: Initial content + license info

---

signature-crate/src/error.rs
signature-crate/src/lib.rs

Replaces the previous error `enum` with a struct that, on `std`, contains an optional cause which is captured as `Box<std::error::Error>`, but is otherwise opaque.
This allows the core signature traits to remain object safe (since they don't need a generic error type) but also allows passing through a provider-specific error type, e.g. for HSMs which may have any number of errors which prevent a signature operation from occuring (e.g. I/O errors, authentication errors, invalid key identifiers).
It also includes downcast methods that conveniently allow extracting provider-specific errors as concrete types if so desired.

Improved signature::error::Error with cause

---

signature-crate/src/digest/mod.rs
signature-crate/src/digest/signer.rs
signature-crate/src/digest/verifier.rs
signature-crate/src/lib.rs
signature-crate/src/signer.rs
signature-crate/src/verifier.rs

Some sweeping refactoring here which hopefully cleans up the project organization and helps simplify its implementation:
- `Sign` => `Signer`, `Verify` => `Verifier`
- Move all `digest`-related functionality under the `digest` module:
- `signature::digest::Signer`
- `signature::digest::Verifier`
- Re-export `::digest::Digest` as `signature::digest::Digest`
- Remove `Send` + `Sync` bounds on traits: if people wants these bounds
they can add them themselves.

Rename to Signer/Verifier; add 'digest' module

---

signature-crate/src/digest/digestable.rs
signature-crate/src/digest/mod.rs
signature-crate/src/digest/signature.rs
signature-crate/src/digest/signer.rs
signature-crate/src/digest/verifier.rs
signature-crate/src/lib.rs

Adds a marker trait for `Signature` types computable as `S(H(m))` where:
- `S`: signature algorithm
- `H`: hash (a.k.a. digest) function
- `m`: message
For signature types that implement this trait, a blanket impl of `Signer` will be provided for all types that `impl signature::digest::Signer`.

Digestable signatures

---

signature-crate/src/signature.rs
signature-crate/src/signer.rs
signature-crate/src/verifier.rs

The current "clever" blanket impl (for which I'm entirely responsible!) seems to have bounds which prevent anything from implementing `Signer` or `Verifier` when the `digest` feature is enabled:
```
= note: conflicting implementation in crate `signature`:
- impl<S, T> signature::signer::Signer<S> for T
where S: signature::signature::DigestSignature, T: signature::signer::DigestSigner<<S as signature::signature::DigestSignature>::Digest, S>;
= note: upstream crates may add new impl of trait `signature::signature::DigestSignature` for type `signatory::ed25519::signature::Signature` in future versions
= note: downstream crates may implement trait `signature::signer::DigestSigner<_, signatory::ed25519::signature::Signature>` for type `ed25519::Ed25519Signer`
```
(I don't even understand the …

Replace Digest-related blanket impls with methods

---

signature-crate/src/signer.rs
signature-crate/src/verifier.rs

This is needed for compatibility with ed25519-dalek's Ed25519ph:
https://docs.rs/ed25519-dalek/1.0.0-pre.1/ed25519_dalek/struct.Keypair.html#method.sign_prehashed
Until const generics land, this API feels a lot cleaner to me. It gets all the `GenericArray` crap out of the way.
It's also misuse resistant in that it ensures the prehashing is done by the relevant hash function, as opposed to the user being able to pass in arbitrary values. There's a potential attack if a verifier accidentally accepts a raw value which isn't the output of a hash function which could allow an attacker to forge signatures:
https://twitter.com/pwuille/status/1063582706288586752

Have DigestSigner/DigestVerifier take Digest instance

---

signature-crate/CHANGES.md
signature-crate/Cargo.toml
signature-crate/signature_derive/Cargo.toml
signature-crate/src/lib.rs
signature-crate/src/prelude.rs

- `signature_derive`: Custom derive support for `Signer`/`Verifier` (#18)
- Have `DigestSigner`/`DigestVerifier` take `Digest` instance (#17)

signature v0.2.0

---

signature-crate/signature_derive/src/lib.rs

Replaces `use` directives with fully qualified paths. This prevents potential name clashes in the event types have the same name as the traits needed for the custom derive.

signature_derive: Use fully qualified paths

---

ed25519/Cargo.toml
ed25519/src/lib.rs

Basic implementation with an initial `ed25519::Signature` type which impls the `signature::Signature` trait.

ed25519: Initial implementation (closes #22)

---

signature-crate/signature_derive/src/lib.rs
signature-crate/src/signature.rs
signature-crate/tests/signature_derive.rs

The `DigestSignature` trait was originally used as the marker trait used by a blanket impl of `Signer` for `DigestSigner` and `Verifier` for `DigestVerifier` (#12, #16).
Unfortunately, this approach turned out to be too inflexible to cover real-world use cases encountered and was replaced with a proc macro (#18). The `DigestSignature` trait is leftover from this, and is no longer needed.
This commit replaces it with a `#[digest(...)]` custom derive attribute which can be used to specify the digest which should be used when computing a signature. This is more flexible than the `DigestSignature` approach, where a single digest needed to be picked at a per-signature level.

signature-crate: Replace DigestSignature with derive attr

---

ecdsa/Cargo.toml
ed25519/Cargo.toml
signature-crate/CHANGES.md
signature-crate/Cargo.toml
signature-crate/signature_derive/Cargo.toml
signature-crate/src/error.rs

- Simplify alloc gating; MSRV 1.36+ ([#28])
- Replace `DigestSignature` trait with `#[digest(...)]` attribute ([#27])
- signature_derive: Upgrade to 1.x proc macro crates ([#26])
[#28]: https://github.com/RustCrypto/signatures/pull/28
[#27]: https://github.com/RustCrypto/signatures/pull/27
[#26]: https://github.com/RustCrypto/signatures/pull/27

signature v0.3.0

---

ed25519/CHANGES.md
ed25519/Cargo.toml
ed25519/README.md
ed25519/src/lib.rs
signature-crate/src/lib.rs

- Upgrade to `signature` v0.3; MSRV 1.36+ ([#29])
[#29]: https://github.com/RustCrypto/signatures/pull/29

ed25519 v0.2.0

---

signature-crate/signature_derive/src/lib.rs
signature-crate/src/signature.rs
signature-crate/tests/signature_derive.rs

This reverts the changes from #27 to replace `DigestSignature` with a custom derive attribute: `#[digest(...)]`
After updating my downstream consumers of this crate to try to use this functionality, I encountered an important case where this falls down: deriving `Signer` and `Verifier` on generic types where the `Digest` *can only* be generically specified as an associated type, as the `yubihsm` crate is doing here:
https://github.com/tendermint/yubihsm-rs/blob/develop/src/ecdsa/signer.rs#L22
The goal of switching to a derive attribute was to make this functionality more flexible and eliminate the need for a marker trait, but in this particular case (one I personally consider very important) it had the opposite effect.

Revert removal of DigestSignature

---

ed25519/CHANGES.md
ed25519/Cargo.toml
ed25519/src/lib.rs

- Upgrade to `signature` 1.0.0-pre.0 ([#34])
[#34]: https://github.com/RustCrypto/signatures/pull/34

ed25519 1.0.0-pre.0

---

signature-crate/src/error.rs
signature-crate/src/lib.rs

This upgrades to the `std::error::Error` features for boxed, downcastable error sources introduced in Rust 1.30, namely switching from `Error::cause` to `Error::source`, which adds a `'static` bound and
therefore allows it to support downcasting.
Additionally, it defines a `BoxError` type incorporating those bounds along with `Send + Sync`, ensuring that `signature::Error` itself is `Send + Sync`, which should improve the ergonomics.

signature: Use `Error::source` instead of `::cause`

---

.travis.yml
README.md
ed25519/Cargo.toml
ed25519/README.md
signature-crate/Cargo.toml
signature-crate/README.md
signature-crate/src/lib.rs
signature-crate/src/signature.rs

The only thing the `signature` crate uses `alloc` for is the `Signature::to_vec` method, which is trivially accomplished otherwise as `sig.as_ref().to_vec()` or various other ways.
By getting rid of it, we can completely get rid of the `alloc` feature, and with that reduce the MSRV back to 1.31.
It might be worth considering a 1.0 release with a higher MSRV so we can leverage `TryFrom`, but for now, this provides wider compatibility by removing a single (mis)feature.

signature: Remove `alloc` feature; MSRV 1.31+

---

ed25519/Cargo.toml
ed25519/src/lib.rs

Serializes and deserializes Ed25519 signatures as 64-byte "octet strings"

ed25519: optional serde support

---

ecdsa/Cargo.toml
ed25519/Cargo.toml
signature-crate/CHANGES.md
signature-crate/Cargo.toml
signature-crate/src/lib.rs

- Use `Error::source` instead of `::cause` ([#37])
- Remove `alloc` feature; MSRV 1.34+ ([#38])
[#38]: https://github.com/RustCrypto/signatures/pull/38
[#37]: https://github.com/RustCrypto/signatures/pull/37

signature 1.0.0-pre.1

---

ed25519/CHANGES.md
ed25519/Cargo.toml
ed25519/src/lib.rs

- Optional `serde` support ([#40])
- Add `TryFrom` impl for `Signature` ([#39])
- Upgrade to `signature` 1.0.0-pre.1 ([#41])
[#41]: https://github.com/RustCrypto/signatures/pull/41
[#40]: https://github.com/RustCrypto/signatures/pull/40
[#39]: https://github.com/RustCrypto/signatures/pull/39

ed25519 v1.0.0-pre.1

---

ecdsa/Cargo.toml
ecdsa/src/curve.rs
ecdsa/src/lib.rs

Adds a `Curve` trait representing short Weirstrass curves suitable for use with ECDSA, along with an initial set of curves and their associated private scalar size.

ecdsa: Initial curves (NIST P-256/384, secp256k1)

---

.travis.yml
build_nostd.sh
build_wasm.sh
ecdsa/Cargo.toml
ed25519/Cargo.toml

Previously only the `signature` crate was being tested

.travis.yml: Test all crates for no_std and WASM compatibility

---

ecdsa/src/curve.rs
ecdsa/src/curve/nistp256.rs
ecdsa/src/curve/nistp384.rs
ecdsa/src/curve/secp256k1.rs
ecdsa/src/fixed_signature.rs
ecdsa/src/lib.rs

Type for representing fixed-sized (a.k.a. "raw") ECDSA signatures

ecdsa: Add FixedSignature type

---

.travis.yml
ecdsa/src/curve.rs
ecdsa/src/fixed_signature.rs

Moves all trait bounds related to `FixedSignature` from the `Curve` trait to the `FixedSignature` type.
This avoids compounding the complexity of the trait bounds on `Curve` when ASN.1 DER signatures are added.

ecdsa: Reorganize size-related trait bounds

---

ecdsa/src/asn1_signature.rs
ecdsa/src/curve.rs
ecdsa/src/curve/nistp256.rs
ecdsa/src/curve/nistp384.rs
ecdsa/src/curve/secp256k1.rs
ecdsa/src/fixed_signature.rs
ecdsa/src/lib.rs
ed25519/src/lib.rs

Support for ASN.1 DER-encoded signatures.
Uses a GenericArray to store the variable-width signature, calculating maximum DER framing overhead using typenum's type-level arithmetic.

ecdsa: Add Asn1Signature type

---

ecdsa/Cargo.toml
ecdsa/src/curve/nistp256.rs
ecdsa/src/curve/nistp384.rs
ecdsa/src/curve/secp256k1.rs

...gated under a `digest` cargo feature.
These are useful when doing `derive(Signer)` or `derive(Verifier)` using the `signature_derive` crate.

ecdsa: Add `DigestSignature` impls

---

ecdsa/src/asn1_signature.rs
ecdsa/src/curve.rs
ecdsa/src/fixed_signature.rs
ecdsa/src/lib.rs
ecdsa/src/scalar_pair.rs

Adapts the following code from BearSSL to support translation between ASN.1 DER encoded and fixed size (a.k.a. "raw") signatures.
This additionally allows eagerly checking that ASN.1 DER-encoded signatures are well-formed.

ecdsa: Asn1Signature <-> FixedSignature translation

---

ecdsa/src/asn1_signature.rs
ecdsa/src/curve.rs
ecdsa/src/curve/nistp256.rs
ecdsa/src/curve/nistp384.rs
ecdsa/src/curve/point.rs
ecdsa/src/curve/secp256k1.rs
ecdsa/src/fixed_signature.rs
ecdsa/src/lib.rs

Adds `CompressedCurvePoint` and `UncompressedCurvePoint` as representations of bytestrings serialized according to the `Elliptic-Curve-Point-to-Octet-String` encoding as defined in section 2.3.3 of SEC 1: Elliptic Curve Cryptography (Version 2.0):
https://www.secg.org/sec1-v2.pdf

ecdsa: elliptic curve points (compressed/uncompressed)

---

ecdsa/src/curve/point.rs

They should be 2 * scalar size + 1-byte (0x04 tag)

ecdsa: Fix uncompressed point sizes

---

Cargo.toml
elliptic-curve-crate/.gitignore
elliptic-curve-crate/Cargo.toml
elliptic-curve-crate/src/error.rs
elliptic-curve-crate/src/lib.rs
elliptic-curve-crate/src/weierstrass.rs
elliptic-curve-crate/src/weierstrass/curve.rs
elliptic-curve-crate/src/weierstrass/curve/nistp256.rs
elliptic-curve-crate/src/weierstrass/curve/nistp384.rs
elliptic-curve-crate/src/weierstrass/curve/secp256k1.rs
elliptic-curve-crate/src/weierstrass/point.rs
elliptic-curve-crate/src/weierstrass/public_key.rs
elliptic-curve-crate/src/weierstrass/secret_key.rs

The `ecdsa` crate contains types, traits, and a complete registry for common Weierstrass curves which is reusable for both the signing and encryption use case.
This extracts the reusable functionality into the `elliptic-curve` crate, with the goal of rewriting the duplicated parts of the current `ecdsa` crate to use types from the `elliptic-curve` crate, and once
that's done, finding a better home, e.g. https://github.com/RustCrypto/traits
It seems we collectively own the following crates:
- `curve25519`
- `ed25519`
- `p256`
- `p384`
- `p521`
- `k256`
...so it would be nice to extract the curve registry in these crates into those crates respectively, e.g. under a hypothetical https://github.com/RustCrypto/elliptic-curves
But for now, this structures the crate the same way the `ecdsa` …

elliptic-curve-crate: Extract from `ecdsa` crate

---

ecdsa/CHANGES.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Re-export PublicKey and SecretKey from the `elliptic-curve` crate ([#61])
[#61]: https://github.com/RustCrypto/signatures/pull/61

ecdsa v0.2.1

---

elliptic-curve-crate/src/p256.rs
elliptic-curve-crate/src/weierstrass/public_key.rs

The compressed and uncompressed encoding APIs now return the corresponding precise type, which can be converted into a `PublicKey` via `PublicKey::from`.

p256: Improve encoding APIs

---

ecdsa/Cargo.toml
elliptic-curve-crate/CHANGES.md
elliptic-curve-crate/Cargo.toml
elliptic-curve-crate/src/lib.rs

- `secp256r1` (P-256) point compression and decompression ([#63], [#64])
- Bump MSRV to 1.37 ([#63])
[#63]: https://github.com/RustCrypto/signatures/pull/63
[#64]: https://github.com/RustCrypto/signatures/pull/64

elliptic-curve v0.2.0

---

ecdsa/CHANGES.md
ecdsa/Cargo.toml
ecdsa/README.md
ecdsa/src/lib.rs

- Upgrade `elliptic-curve` crate to v0.2.0; MSRV 1.37+ ([#65])
[#65]: https://github.com/RustCrypto/signatures/pull/65

ecdsa v0.3.0

---

ecdsa/Cargo.toml
ecdsa/src/curve.rs
ecdsa/src/curve/nistp256.rs
ecdsa/src/curve/nistp384.rs
ecdsa/src/curve/secp256k1.rs
ecdsa/src/lib.rs

...and use the `p256`, `p384`, and `k256` crates

Upgrade 'elliptic-curve' crate to v0.3

---

ecdsa/CHANGES.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Upgrade `elliptic-curve` crate to v0.3.0; make curves cargo features ([#68])
[#68]: https://github.com/RustCrypto/signatures/pull/68

ecdsa v0.4.0

---

README.md
ed25519/CHANGES.md
ed25519/Cargo.toml
ed25519/README.md
ed25519/src/lib.rs

- Upgrade to `signature` crate v1.0.0-pre.3 ([#71])
- Bump MSRV to 1.37 ([#63])
[#71]: https://github.com/RustCrypto/signatures/pull/71
[#63]: https://github.com/RustCrypto/signatures/pull/63

ed25519 v1.0.0-pre.2

---

ecdsa/Cargo.toml
ecdsa/src/lib.rs

Pre-release with bump to `signature` crate v1.0.0-pre.3. See:
https://github.com/RustCrypto/traits/issues/78

ecdsa v0.5.0-pre

---

Cargo.lock
ed25519/CHANGES.md
ed25519/Cargo.toml
ed25519/src/lib.rs

- Upgrade to `signature` crate v1.0.0-pre.3 ([#74])
- Bump MSRV to 1.40 ([#75])
[#74]: https://github.com/RustCrypto/signatures/pull/74
[#75]: https://github.com/RustCrypto/signatures/pull/75

ed25519 v1.0.0-pre.3

---

Cargo.lock
ed25519/CHANGES.md
ed25519/Cargo.toml
ed25519/src/lib.rs

- Avoid serializing a length prefix with `serde` ([#78])
[#78]: https://github.com/RustCrypto/signatures/pull/78

ed25519 v1.0.0-pre.4

---

Cargo.lock
README.md
ed25519/CHANGES.md
ed25519/Cargo.toml
ed25519/src/lib.rs

- Upgrade `signature` crate to v1.0 final release ([#80])
[#80]: https://github.com/RustCrypto/signatures/pull/80

ed25519 v1.0.0

---

Cargo.lock
ecdsa/CHANGES.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Upgrade `signature` crate to v1.0 final release ([#80])
[#80]: https://github.com/RustCrypto/signatures/pull/80

ecdsa v0.5.0

---

ed25519/src/lib.rs

Adds usage examples of how to write code which is generic over an underlying signing provider.

ed25519: improve usage documentation

---

Cargo.lock
ecdsa/Cargo.toml

Release announcement:
https://www.reddit.com/r/rust/comments/gbjsr9/ann_rustcrypto_p256_and_k256_v020_pure_rust_nist/

Bump `p256` and `k256` to v0.2

---

.github/workflows/ecdsa.yml
.github/workflows/ed25519.yml
Cargo.lock
README.md
ecdsa/Cargo.toml
ecdsa/README.md
ecdsa/src/asn1_signature.rs
ecdsa/src/convert.rs
ecdsa/src/fixed_signature.rs
ecdsa/src/lib.rs
ed25519/README.md
ed25519/src/lib.rs

Bumps the following crate dependencies, which all now depend on `generic-array` v0.14:
- `elliptic-curve` v0.4.0
- `k256` v0.3.0
- `p256` v0.3.0
- `p384` v0.2.0
Also re-exports `generic-array` from the `elliptic-curve` crate rather than depending on it directly, which simplifies upgrades.

ecdsa: bump all elliptic curve crates; MSRV 1.41+

---

Cargo.lock
ecdsa/Cargo.toml

These both depend on the `digest` v0.9 crate

ecdsa: upgrade to `signature` ~1.1.0; `sha` v0.9

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- Upgrade to `signature` ~1.1.0; `sha` v0.9 ([#87])
- Bump all elliptic curve crates; MSRV 1.41+ ([#86])
[#87]: https://github.com/RustCrypto/signatures/pull/87
[#86]: https://github.com/RustCrypto/signatures/pull/86

ecdsa v0.6.0

---

ecdsa/src/asn1_signature.rs
ecdsa/src/curve/secp256k1.rs
ecdsa/src/curve/secp256k1/recoverable_signature.rs
ecdsa/src/fixed_signature.rs
ecdsa/src/lib.rs

Adds a signature type for Ethereum-style recoverable signatures.

ecdsa::curve::secp256k1::RecoverableSignature

---

ecdsa/Cargo.toml
ecdsa/src/curve.rs
ecdsa/src/curve/secp256k1/recoverable_signature.rs
ecdsa/src/lib.rs

Uses the nightly-only `doc_cfg` feature to document which modules/types are gated behind cargo features (namely `k256`, `p256`, and `p384`)
This is intended for use with https://docs.rs

ecdsa: add doc_cfg

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- `doc_cfg` attributes for https://docs.rs ([#91])
- `ecdsa::curve::secp256k1::RecoverableSignature` ([#90])
[#91]: https://github.com/RustCrypto/signatures/pull/91
[#90]: https://github.com/RustCrypto/signatures/pull/90

ecdsa v0.6.1

---

Cargo.lock
Cargo.toml
ecdsa/Cargo.toml

Adds a `[patch.crates-io]` directive so we can work off the latest versions of the https://github.com/RustCrypto/elliptic-curves crates.
This is a breaking change for the `ecdsa` crate and makes it unreleasable until releases of the elliptic curve crates happen,
but will allow us to implement a number of new features which require a curve arithmetic implementation.

Cargo.toml: fetch RustCrypto/elliptic-curves crates from git

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/convert.rs
ecdsa/src/curve/secp256k1.rs
ecdsa/src/curve/secp256k1/normalize_s.rs

Adds `normalize_s` method to `secp256k1::{Asn1Signature, FixedSignature}` when the (new) `k256-arithmetic` feature is enabled.
This normalizes the s-component of ECDSA signatures in order to make them non-malleable as described in [BIP 0062: Dealing with Malleability](https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki).

ecdsa: implement secp256k1 low-S normalization

---

Cargo.lock
ecdsa/Cargo.toml

This commit isn't intended to be a release, but just bumps the version number in Cargo.toml to `-pre` to distinguish it from the currently released v0.6.1.
Several backwards incompatible / semver breaking changes have been introduced since the release.
It also updates `elliptic-curve` to v0.5.0-pre, which was similarly bumped to a `-pre` version in:
https://github.com/RustCrypto/traits/pull/215

ecdsa: bump version to v0.7.0-pre

---

ecdsa/Cargo.toml
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs

The `DigestPrimitive` trait, intended to be implemented within a crate which impls `elliptic_curve::weierstrass::Curve`, provides a blanket impl of `PrehashSignature` for `ecdsa::Signature<C: Curve>`.
This is a small hack needed to work around the fact that the ECDSA signature trait now lies in an external crate, so crates which implement a specific curve can no longer impl traits on `ecdsa::Signature`.

ecdsa: add DigestPrimitive

---

ecdsa/src/hazmat.rs

It previously used `elliptic_curve::Error` instead by mistake

ecdsa: use signature::Error in `hazmat` module

---

ecdsa/src/hazmat.rs

Avoids making unnecessary copies

ecdsa: have SignPrimitive borrow scalars

---

ecdsa/src/asn1.rs
ecdsa/src/lib.rs

This commit renames `asn1::Document` to `asn1::Signature`.
This means we now have the following types:
- `ecdsa::Signature`: fixed-sized encoding
- `ecdsa::asn1::Signature`: ASN.1 DER encoding
Additionally this commit adds an impl of the `signature::Signature` trait for `asn1::Signature`, promoting it back to a first-class signature type. This allows ECDSA `signature::Signer` impls to directly produce ASN.1 encoded signatures again without transcoding, if they so desire.

ecdsa: rename `asn1::Signature`; impl `signature` trait

---

ecdsa/Cargo.toml
ecdsa/src/dev.rs
ecdsa/src/lib.rs

Adds a `dev` module ala the ones in the trait crates which contains `new_signing_test` and `new_verification_test` macros which implement a basic set of tests for implementers of `SignPrimitive` and `VerifyPrimitive` respectively.
Ideally this would implement something close to the set of tests described in the [FIPS 186-4 ECDSA Validation System (ECDSA2VS)](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/dss2/ecdsa2vs.pdf), however for now it tests basic signing, verification, and a verification failure in the event the `s` component of the signature has an incorrect value.
Eventually it'd probably be good to convert to using `blobby` for consistency with the other `dev` modules, however for now it specifies a `TestVector` struct which the …

ecdsa: initial `dev` module with `new_*_test` macros

---

Cargo.lock
ecdsa/src/asn1.rs
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs

Updates usages of the `elliptic-curve` crate API to incorporate the changes from https://github.com/RustCrypto/traits/pull/223

ecdsa: implement RustCrypto/traits#223 updates

---

Cargo.lock
ecdsa/src/hazmat.rs

...and remove `masking_scalar`.
This API allows the inversion masking process to be handled outside of the ECDSA implementation itself (potentially generically in a way that can work across elliptic curves).

ecdsa: make SignPrimitive's ephemeral scalar generic

---

ecdsa/src/dev.rs
ecdsa/src/hazmat.rs

Changes the `Into` bound on the `K` generic parameter to `SignPrimitive` to an `AsRef<C::Scalar>`. This avoids making unnecessary copies as well as simplifying type inference.
Also fixes the macros in the `dev` module to use the new two parameter `SignPrimitive` interface.

ecdsa: SignPrimitive bounds and dev macro fixups

---

.github/workflows/ecdsa.yml
Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/signer.rs

Adds a `ecdsa::signer::Signer` facade which handles parsing of `SecretKey` data and zeroization of the private scalar.
The implementation is generic over the elliptic curve and digest function, providing a `RandomizedDigestSigner` impl, and also when the curve type impls `DigestPrimitive`, a `RandomizedSigner` impl.

ecdsa: Signer facade (gated under `signer` feature)

---

.github/workflows/ecdsa.yml
Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/lib.rs
ecdsa/src/verifier.rs

Adds a `ecdsa::verifier::Verifier` facade which handles parsing of `PublicKey` and computing digests of messages, ala the `Signer` facade added in #109.
The implementation is generic over the elliptic curve and digest function, providing a `DigestVerifier` impl, and when the curve type impls `DigestPrimitive`, a `Verifier` impl as well.

ecdsa: Verifier facade (gated under `verifier` feature)

---

Cargo.lock
ecdsa/src/hazmat.rs

Trait for signature algorithm implementations that support public key recovery, with a blanket impl for `SignPrimitive`.

ecdsa: add hazmat::RecoverableSignPrimitive

---

Cargo.lock
ecdsa/src/asn1.rs
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs

ecdsa: rename ScalarBytes to ElementBytes

---

Cargo.lock
ecdsa/src/signer.rs
ecdsa/src/verifier.rs

Uses the new `FromBytes` trait introduced in RustCrypto/traits#247

ecdsa: use new `elliptic_curve::encoding` module

---

Cargo.lock
ecdsa/src/lib.rs

Provides generalized support for low S normalization, bounded on a newly introduced `NormalizeLow` trait and a `Signature::normalize_s` method which handles updating a signature value.

ecdsa: low-S normalization support

---

ecdsa/src/lib.rs

...conditionally when the underlying `GenericArray` supports `Copy`

ecdsa: impl Copy on Signature

---

ecdsa/src/lib.rs

...to indicate whether normalization occurred or not, and have this propagate via `Signature::normalize_s`.

ecdsa: have NormalizeLow return a bool

---

ecdsa/src/hazmat.rs

Adds an associated `RecoverableSignature` type to `RecoverableSignPrimitive`.
This allows the primitive to handle construction of the full signature, which makes it possible to add normalization at the generic `ecdsa::signer::Signer` level.

ecdsa: add associated sig type to RecoverableSignPrimitive

---

Cargo.lock
Cargo.toml
ecdsa/Cargo.toml
ecdsa/src/asn1.rs

Release notes: https://github.com/RustCrypto/traits/pull/254

ecdsa: Bump `elliptic-curve` crate to v0.5 release

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- `hazmat` traits: `SignPrimitive`, `RecoverableSignPrimitive`, `VerifyPrimitive`, `DigestPrimitive` ([#96], [#99], [#107], [#111])
- `dev` module ([#103])
- `NormalizeLow` trait ([#115], [#118], [#119])
- `Copy` impl on `Signature` ([#117])
- `RecoverableSignPrimitive` ([#120])
- Bumped `elliptic-curve` crate to v0.5 release ([#123])
- Renamed `FixedSignature` to `ecdsa::Signature` ([#98])
- Renamed `Asn1Signature` to `ecdsa::asn1::Signature` ([#98], [#102])
- Curve-specific types - migrated to `k256`, `p256`, `p384` crates ([#96])
[#96]: https://github.com/RustCrypto/signatures/pull/96
[#98]: https://github.com/RustCrypto/signatures/pull/98
[#99]: https://github.com/RustCrypto/signatures/pull/99
[#102]: https://github.com/RustCrypto/signatures/pull/102
[#103]: …

ecdsa v0.7.0

---

ecdsa/Cargo.toml

Originally this was trying to hide the `hazmat` module, but several features have been added since then (`rand`, `signer`, `verifier`) which need the `hazmat` module enabled.

ecdsa/Cargo.toml: use `all-features = true` on docs.rs

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Use `all-features = true` on docs.rs ([#126])
[#126]: https://github.com/RustCrypto/signatures/pull/126

ecdsa v0.7.1

---

Cargo.lock
Cargo.toml
ecdsa/Cargo.toml
ecdsa/src/lib.rs
ecdsa/src/verifier.rs

Uses the new `sec1::EncodedPoint` type introduced in RustCrypto/traits#264

ecdsa: use newly refactored sec1::EncodedPoint

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/signer.rs
ecdsa/src/signer/rfc6979.rs

Adds a deterministic signing mode based on RFC6979. Closes #124.
~~This could be further extended to bolster the security when using `RandomizedSigner` using the method described in Section 3.6.~~
Edit: went ahead and made `RandomizedDigestSigner` use an RFC6979-style derivation but supplying some additional data from the RNG as input. It was easy enough.

ecdsa: implement RFC6979 ephemeral scalar generation

---

ecdsa/src/dev.rs
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/signer.rs
ecdsa/src/signer/rfc6979.rs
ecdsa/src/verifier.rs

- Uses the `FromDigest` trait to automatically convert message digests into a `C::Scalar` value
- Updates `SignPrimitive` and `VerifyPrimitive` to accept a scalar
- Updates the `dev` module accordingly with the above
- Exposes the `ecdsa::signer::rfc6979` module and makes the `generate_k` method `pub`

ecdsa: use FromDigest trait; RFC6979 fixups

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/dev.rs
ecdsa/src/dev/curve.rs
ecdsa/src/signer/rfc6979.rs

Adds a test that the RFC6979 implementation produces the correct ephemeral scalar (`k`) for the test vector in RFC 6979 Appendix 2.5:
https://tools.ietf.org/html/rfc6979#appendix-A.2.5
This unfortunately requires basic scalar support, as RFC6979 uses rejection sampling to select a `k` value, so this commit also contains the rudiments of a P-256 scalar implementation necessary to implement the test.
Hopefully this will be useful for testing other aspects of ECDSA, or potentially ensuring that the scalars of an ECDSA signature are in-range generically, even if no curve arithmetic backend is available.

ecdsa: add RFC6979 test (plus `dev::curve` module)

---

Cargo.lock
ecdsa/src/asn1.rs
ecdsa/src/dev/curve.rs
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/signer.rs
ecdsa/src/signer/rfc6979.rs
ecdsa/src/verifier.rs

See: https://github.com/RustCrypto/traits/pull/282

ecdsa: rename Curve::ElementSize => FieldSize

---

ecdsa/src/hazmat.rs

This is really a concern of the `k256` crate and isn't helpful to generalize to other curves.

ecdsa: remove RecoverableSignPrimitive

---

ecdsa/Cargo.toml
ecdsa/src/asn1.rs
ecdsa/src/lib.rs

Adds a basic `alloc` feature which enables a `to_bytes()` method on `asn1::Signature`.

ecdsa: add `alloc` feature

---

ecdsa/src/asn1.rs
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs

Adds a `CheckSignatureBytes` trait with a default impl that ensures neither the `r` nor `s` components of a signature are all-zero.
Includes a blanket impl of `CheckSignatureBytes` for all curves with the `Arithmetic` trait defined (and thus access to `C::Scalar`). This performs a better check that both `r` and `s` do not overflow the curve's order and are non-zero (using `NonZeroScalar`).
Together these allow conditionally defining `ecdsa::Signature::r` and `::s` methods which permit infallible access to `NonZeroScalar<C>`, rather than the previous implementation which returns bytes.
All of the above is a compromise which allows for crates which do not provide a curve arithmetic backend to still assert some checks on the signature values, but also ensure that signatures are well-formed, …

ecdsa: add CheckSignatureBytes trait + NonZeroScalar components

---

Cargo.lock
ecdsa/src/dev/curve.rs
ecdsa/src/lib.rs
ecdsa/src/rfc6979.rs
ecdsa/src/sign.rs

ecdsa: rename ElementBytes => FieldBytes

---

Cargo.lock
ecdsa/src/lib.rs
ecdsa/src/sign.rs

ecdsa: SecretKey updates

---

Cargo.lock
ecdsa/src/dev.rs
ecdsa/src/dev/curve.rs
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/rfc6979.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Accompanying changes for RustCrypto/traits#300.

ecdsa: refactor ProjectiveArithmetic trait

---

Cargo.lock
Cargo.toml
ecdsa/Cargo.toml

Release notes: https://github.com/RustCrypto/traits/pull/302

ecdsa: bump `elliptic-curve` crate dependency to v0.6

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- `CheckSignatureBytes` trait ([#151])
- Add `Signature::r`/`::s` methods which return `NonZeroScalar`values ([#151])
- `alloc` feature ([#150])
- Impl `From<&VerifyKey<C>>` for `EncodedPoint<C>` ([#144])
- Serialization methods for `SigningKey`/`VerifyKey` ([#143])
- RFC6979-based deterministic signatures ([#133], [#134], [#136])
- Bump `elliptic-curve` crate dependency to v0.6 ([#165])
- Use `ProjectiveArithmetic` trait ([#164])
- Rename `ElementBytes` to `FieldBytes` ([#160])
- Use `ff` and `group` crates to v0.8 ([#156])
- MSRV 1.44+ ([#156])
- Remove `rand` feature; make `rand_core` a hard dependency ([#154])
- Use `impl Into<ElementBytes>` bounds on `Signature::from_scalars` ([#149])
- Derive `Clone`, `Debug`, `Eq`, and `Ord` on `VerifyKey` ([#148])
- Renamed `{Signer, Verifier}` => …

ecdsa v0.8.0

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Conditional `Copy` impl on `VerifyKey<C>` ([#171])
[#171]: https://github.com/RustCrypto/signatures/pull/171

ecdsa v0.8.1

---

ecdsa/src/hazmat.rs

This reverts commit a03cda2372b3d931f44db2c65634c89441e9204c (#146)
Revives `RecoverableSignPrimitive` since there have been some requests/use cases for it.
First, there was interest in supporting such a primitive for `p256`:
https://github.com/RustCrypto/elliptic-curves/pull/184
Second, it would be helpful for Ethereum, since it seems implementations often use (HMAC-DRBG-)SHA-256 for RFC6979, but Keccak256 as the message digest function. Exposing this interface would allow for such combinations which aren't possible otherwise.

Revert "ecdsa: remove RecoverableSignPrimitive"

---

ecdsa/src/hazmat.rs

...as opposed to using a separate associated type.
As it were, this is how the method is documented. It was changed at some point but the comments were never updated.

ecdsa: have RecoverableSignPrimitive return a bool flag

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- `RecoverableSignPrimitive` ([#174], [#175])
[#174]: https://github.com/RustCrypto/signatures/pull/174
[#175]: https://github.com/RustCrypto/signatures/pull/175

ecdsa v0.8.2

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- 32-bit builds for the `dev` feature ([#177])
[#177]: https://github.com/RustCrypto/signatures/pull/177

ecdsa v0.8.3

---

ed25519/src/lib.rs

The presence of the `intra_doc_link_resolution_failure` lint now breaks cargo-tarpaulin:
https://github.com/RustCrypto/signatures/pull/180/checks?check_run_id=1228016160
This PR removes it.

ed25519: fix tarpaulin

---

ecdsa/src/sign.rs

The `ecdsa` crate no longer builds on `nightly`, possibly due to:
https://github.com/rust-lang/rust/issues/77638
Unfortunately this means rustdoc builds on https://docs.rs fail!
This commit works around the issue.

ecdsa: work around nightly-2020-10-06 breakage

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Work around `nightly-2020-10-06` breakage ([#180])
[#180]: https://github.com/RustCrypto/signatures/pull/180

ecdsa v0.8.4

---

ecdsa/src/lib.rs

The logic was reversed and it was rejecting valid signatures

ecdsa: fix default impl of CheckSignatureBytes

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Bug in default impl of CheckSignatureBytes ([#184])
[#184]: https://github.com/RustCrypto/signatures/pull/184

ecdsa v0.8.5

---

Cargo.lock
ed25519/CHANGES.md
ed25519/Cargo.toml
ed25519/src/lib.rs

- `ring-compat` usage example ([#187])
[#187]: https://github.com/RustCrypto/signatures/pull/187

ed25519 v1.0.3

---

ecdsa/src/lib.rs

ecdsa: add more toplevel rustdoc

---

Cargo.lock
Cargo.toml
ecdsa/Cargo.toml
ecdsa/README.md
ecdsa/src/lib.rs
ecdsa/src/verify.rs

ecdsa: bump `elliptic-curve` dependency to v0.7.0-pre

---

Cargo.lock
ecdsa/src/sign.rs

The latter wraps up many of the concerns of secret key management, including computing public keys, encoding/decoding, and zeroization.

ecdsa: make SigningKey a newtype of elliptic_curve::SecretKey

---

Cargo.lock
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Uses simpler bounds implemented in RustCrypto/traits#378

ecdsa: simplify VerifyKey trait bounds

---

ecdsa/src/lib.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Per the discussion in #196, renames `VerifyKey` => `VerifyingKey` for better consistency with `SigningKey`.

ecdsa: rename VerifyKey to VerifyingKey

---

ecdsa/src/verify.rs

The derived impl does not have the correct bounds

ecdsa: explicit Copy impl for VerifyKey

---

Cargo.lock
ecdsa/src/verify.rs

This reverts commit 91cb79eddef19bede669f5ad79a1a7deb967706e.
Fixed the root cause upstream in the `elliptic-curve` crate:
https://github.com/RustCrypto/traits/pull/379

Revert "ecdsa: explicit Copy impl for VerifyKey (#201)"

---

ecdsa/src/sign.rs

More consistent with the rest of the method names in the `elliptic-curve` crate and `VerifyingKey`

ecdsa: rename `SigningKey::new()` to `::from_bytes`

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- PKCS#8 support ([#203])
- Bump `elliptic-curve` crate dependency to v0.7; MSRV 1.46+ ([#204])
- Rename `VerifyKey` to `VerifyingKey` ([#200])
- Rename `VerifyingKey::new()` to `::from_sec1_bytes()` ([#198])
- Rename `SigningKey::new()` to `::from_bytes()` ([#205])
- Additional validity checks on ASN.1 DER-encoded signatures ([#192])
[#205]: https://github.com/RustCrypto/signatures/pull/205
[#204]: https://github.com/RustCrypto/signatures/pull/204
[#203]: https://github.com/RustCrypto/signatures/pull/203
[#200]: https://github.com/RustCrypto/signatures/pull/200
[#198]: https://github.com/RustCrypto/signatures/pull/198
[#192]: https://github.com/RustCrypto/signatures/pull/192

ecdsa v0.9.0

---

ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Bump `elliptic-curve` dependency to v0.8 ([#215])
[#215]: https://github.com/RustCrypto/signatures/pull/215

ecdsa v0.10.0

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

This is a release solely to trigger a rebuild on docs.rs.
The previous build failed due to a `nightly` regression in the upstream `elliptic-curve` crate:
https://github.com/RustCrypto/traits/pull/412
Crate is otherwise unchanged from the previous release.

ecdsa v0.10.1

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Bump `elliptic-curve` crate to v0.8.3 ([#218])
- Use the `dev` module from the `elliptic-curve` crate ([#218])
[#218]: https://github.com/RustCrypto/signatures/pull/218

ecdsa v0.10.2

---

ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/rfc6979.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

These are no longer needed as of `ff` v0.9:
https://github.com/zkcrypto/ff/pull/43

ecdsa: remove FieldBytes bounds

---

Cargo.lock
ecdsa/src/sign.rs

This is mostly to ensure that recent changes to the `elliptic-curve` crate didn't break anything in the `ecdsa` crate.

Cargo.lock: bump deps

---

Cargo.lock
ecdsa/src/lib.rs
ecdsa/src/rfc6979.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

See: https://github.com/RustCrypto/traits/pull/487

Cargo.lock: bump deps to flat-namespaced `elliptic-curve` crate

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/lib.rs

`ecdsa` v0.11 is pretty much ready to release aside from updates to `digest` and `hmac`.
This prerelease will allow publishing prereleases of the [RustCrypto/elliptic-curve](https://github.com/RustCrypto/elliptic-curves/) crates with an updated `rand_core` dependency, and then we can bump `digest`/`hmac` for a final release.

ecdsa v0.11.0-pre.1

---

ecdsa/src/rfc6979.rs

This is simply a matter of iterating the hashing of self.v until
sufficient output bytes have been produced.
This is necessary for the upcoming DSA implementation.

Change HmacDrbg to support variable output size

---

ed25519/src/lib.rs

The first portion of the example in `lib.rs` does not match the second portion for `HelloVerifier` member names - and will fail to compile when combined.
This pull-request aligns the member names so the example works when the two halves are put together.

Fix compile error in ed25519 example.

---

ecdsa/src/hazmat.rs

This is my best understanding from what I was told in another issue.

Clarify purpose of FromDigest trait

---

ecdsa/src/der.rs

This assertion duplicates an error handling check immediately below it.
It's likely a remnant of the retrofitting of the `der` crate for signature parsing.

ecdsa: remove useless debug assert

---

.github/workflows/ecdsa.yml
Cargo.lock
ecdsa/README.md
ecdsa/src/lib.rs
ed25519/README.md

This commit upgrades the following dependencies:
- `base64` v1.0
- `elliptic-curve` v0.9.5
- `pkcs8` v0.5.5

ecdsa: bump base64ct, elliptic-curve, and pkcs8; MSRV 1.47+

---

ecdsa/src/der.rs
ecdsa/src/lib.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Removes superfluous modules from the public API, flattening it down and also removing superfluous re-exports.

ecdsa: flatten and simplify public API

---

ecdsa/src/dev.rs
ecdsa/src/hazmat.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Previously this key type was named `VerifyKey` and was changed to `VerifyingKey` for more consistency with `SigningKey`.
However, some usages of `verify_key` were not updated. This commit updates those names to be consistent with the type name.

ecdsa: use `verifying_key` name consistently

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/der.rs
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

The longer-term goal of this change is to eliminate the `CheckSignatureBytes` trait by having a generic implementation which uses the `Order::ORDER` constant.
For now, just ensure that the curve's order is defined.

ecdsa: bound curve implementations on Order trait

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/tests/lib.rs

Uses a generic implementation for checking that the scalars in a signature are in range which doesn't require a curve arithmetic backend.

ecdsa: replace CheckSignatureBytes with Order

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/lib.rs

Bumps the `elliptic-curve` crate dependency to v0.9.10, and uses the newly added `ScalarBytes` type to `impl TryFrom<&[u8]> for Signature<C>`

ecdsa: bump `elliptic-curve` to v0.9.10; use `ScalarBytes`

---

Cargo.lock
ed25519/CHANGES.md
ed25519/Cargo.toml

- Bump `ring-compat` to v0.2; MSRV 1.47+ ([#289])
- Compile error in example ([#246])
[#246]: https://github.com/RustCrypto/signatures/pull/246
[#289]: https://github.com/RustCrypto/signatures/pull/289

ed25519 v1.1.0

---

Cargo.lock
ed25519/src/lib.rs

`VerifyKey` was renamed to `VerifyingKey`

ed25519: updates for `ring-compat` v0.2.1

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- `Ord` and `PartialOrd` impls on VerifyingKey ([#298], [#299])
- Bump `elliptic-curve` dependency to v0.9.12 ([#299])
[#298]: https://github.com/RustCrypto/signatures/pull/298
[#299]: https://github.com/RustCrypto/signatures/pull/299

ecdsa v0.11.1

---

.github/workflows/ecdsa.yml
.github/workflows/workspace.yml
Cargo.lock
Cargo.toml
ecdsa/Cargo.toml
ecdsa/README.md
ecdsa/src/der.rs
ecdsa/src/dev.rs
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/rfc6979.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Sourced via git
Also includes bump to `der` crate v0.4.0-pre

ecdsa: bump `elliptic-curve` crate to v0.10.0-pre; MSRV 1.51+

---

Cargo.lock
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/rfc6979.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

The newly introduced `ScalarArithmetic` trait captures these bounds automatically:
https://github.com/RustCrypto/traits/pull/654

ecdsa: remove PrimeField bounds; leverage ScalarArithmetic

---

ecdsa/src/dev.rs

The `ff` crate is now re-exported as `elliptic_curve::group::ff`.

ecdsa: fix `ff` imports in test gen macros

---

ecdsa/src/dev.rs

ecdsa: fix typo

---

Cargo.lock
ecdsa/src/sign.rs
ecdsa/src/verify.rs

These bounds are now captured by the `*Arithmetic` traits

ecdsa: remove unnecessary bounds on AffinePoint/ProjectivePoint

---

Cargo.lock
ecdsa/src/der.rs
ecdsa/src/dev.rs
ecdsa/src/lib.rs

Incorporates changes from https://github.com/RustCrypto/traits/pull/660 and https://github.com/RustCrypto/utils/pull/488

ecdsa: bump `crypto-bigint` to v0.2.0-pre

---

ecdsa/src/dev.rs

They weren't updated to incorporate the changes from #313

ecdsa: fix `dev` module macros

---

Cargo.lock
Cargo.toml
ecdsa/Cargo.toml

Also bumps: `der` => v0.4
Changelog: https://github.com/RustCrypto/traits/pull/663

ecdsa: bump `elliptic-curve` crate dependency to v0.10

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Bump `der` crate to v0.4 ([#302], [#315])
- Bump `elliptic-curve` crate dependency to v0.10 ([#315])
- MSRV 1.51+ ([#302], [#315])
- Bounds now expressed via `*Arithmetic` traits ([#303], [#312])
[#302]: https://github.com/RustCrypto/signatures/pull/302
[#303]: https://github.com/RustCrypto/signatures/pull/303
[#315]: https://github.com/RustCrypto/signatures/pull/315

ecdsa v0.12.0

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/verify.rs

Analogous change to https://github.com/RustCrypto/traits/pull/667

ecdsa: add explicit `Copy` bounds on `VerifyingKey`

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Explicit `Copy` bounds on `VerifyingKey` ([#318])
[#318]: https://github.com/RustCrypto/signatures/pull/318

ecdsa v0.12.1

---

ecdsa/src/sign.rs

I am not exactly sure what is the convention for Drop implementations, but it seems like `SigningKey` needs one.

Add zeroization on drop for SigningKey

---

.github/workflows/workspace.yml
ed25519/src/lib.rs

This crate is 1.0 and fixing this nit would arguably be a breaking change.
This commit ignores it and adds a TODO to fix it eventually.

ed25519: ignore clippy nit for `Signature::to_bytes()`

---

ecdsa/Cargo.toml
ecdsa/src/der.rs
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Simplifies the method signatures

ecdsa: use signature::Result alias

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Impl `TryFrom<&[u8]>` for `Verifying<C>` ([#329])
- Impl `TryFrom<&[u8]>` for `SigningKey<C>` ([#330])
- Use `signature::Result` alias ([#331])
[#329]: https://github.com/RustCrypto/signatures/pull/329
[#330]: https://github.com/RustCrypto/signatures/pull/330
[#331]: https://github.com/RustCrypto/signatures/pull/331

ecdsa v0.12.3

---

Cargo.lock
ed25519/Cargo.toml
ed25519/src/lib.rs

This allows consumers to opt-in to `serde_bytes` support by setting the
`std`, `serde`, and `serde_bytes` features. This makes it convenient to
optimise (de)serialization for formats with efficient byte array
encodings, e.g.
#[derive(serde::Deserialize, serde::Serialize)]
struct MySignature {
#[serde(with = "serde_bytes")]
signature: ed25519::Signature,
}
Without first-class support for `serde_bytes`, consumers would have to
write their own (de)serialization machinery for this common case.

feat(ed255519): Introduce `serde_bytes` optional dependency

---

ed25519/src/lib.rs

Following up from https://github.com/RustCrypto/signatures/pull/337#issuecomment-884385125, I went ahead and wrote a sentence about each feature.
Screenshot of the new section rendered locally:

doc(ed25519): Add crate documentation for features

---

Cargo.lock
ed25519/CHANGELOG.md
ed25519/Cargo.toml
ed25519/src/lib.rs

- `serde_bytes` optional dependency ([#337])
[#337]: https://github.com/RustCrypto/signatures/pull/337

ed25519 v1.2.0

---

ecdsa/src/sign.rs
ecdsa/src/verify.rs

Adds previously missing trait impls for `SigningKey<C>`.
The `Eq`/`PartialEq` impls use `ConstantTimeEq` internally to compare signing keys in constant-time.
Closes #344

ecdsa: impl `Clone`, `Debug`, `*Eq` for SigningKey

---

Cargo.lock
Cargo.toml
ecdsa/Cargo.toml
ecdsa/src/lib.rs
ecdsa/src/rfc6979.rs

Sourced via git.
This includes transitive updates to `ff` and `group` v0.11.

ecdsa: bump `elliptic-curve` to v0.11.0-pre

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/dev.rs
ecdsa/src/lib.rs
ecdsa/src/sign.rs

Updates the test macros to be compatible with the changes from #352.

ecdsa: fix test macros

---

ecdsa/src/lib.rs

This was previously triggering a panic because `CtOption` eagerly evaluates both branches, causing a panic to be triggered in the success case because it branched even in the success case.

ecdsa: fix `CtOption`-related regression in component accessors

---

ecdsa/src/lib.rs

Changes the low-S normalization APIs to return `Option<Self>` rather than mutating `Signature` in-place.
This allows for more functional patterns when working with these APIs.

ecdsa: make `Signature::normalize_s` non-mutating

---

.github/workflows/ecdsa.yml
Cargo.lock
Cargo.toml
ecdsa/Cargo.toml
ecdsa/src/dev.rs
ecdsa/src/lib.rs
ecdsa/src/sign.rs

Corresponding changes for RustCrypto/traits#732

ecdsa: switch from `ScalarBytes<C>` to `ScalarCore<C>`

---

Cargo.lock
ecdsa/src/der.rs
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/rfc6979.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Switches from `weierstrass::Curve` to the `PrimeCurve` trait added in RustCrypto/traits#737.

ecdsa: use `PrimeCurve` trait

---

Cargo.lock
ecdsa/src/sign.rs

Replaces explicit `Zeroize`  bounds with the ones introduced in RustCrypto/traits#738.

ecdsa: use mandatory `DefaultIsZeroes` bounds

---

.github/workflows/ecdsa.yml
.github/workflows/workspace.yml
Cargo.lock
ecdsa/README.md
ecdsa/src/lib.rs

Introduced in RustCrypto/elliptic-curve#739

ecdsa: MSRV 1.52

---

ecdsa/src/lib.rs

Eliminates a manually written check with a higher-level method for ensuring R/S are nonzero.

ecdsa: use `ScalarCore::is_zero` to validate R/S scalars

---

Cargo.lock
Cargo.toml

Updates `elliptic-curve` to a new version which uses the (unreleased) `sec1 crate.
See RustCrypto/traits#765

elliptic-curve: bump version; add `sec1` crate patch

---

Cargo.lock
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Incorporates upstream changes from:
https://github.com/RustCrypto/traits/pull/771

ecdsa: use `sha1` crate's `EncodedPoint`

---

Cargo.lock
Cargo.toml

Bumps the `elliptic-curve` git hash and removes the patch dependencies

ecdsa: use the `sec1` crate release

---

Cargo.lock
ecdsa/src/dev.rs
ecdsa/src/hazmat.rs
ecdsa/src/rfc6979.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Now that we have a trait for expressing modular reductions, it can replace the `FromDigest` trait, with the output of a given digest function passed as an input to a modular reduction.

ecdsa: replace `FromDigest` trait with `Reduce`

---

Cargo.lock
ecdsa/src/verify.rs

See: https://github.com/RustCrypto/traits/pull/782

ecdsa: update to use new `FromEncodedPoint` trait

---

Cargo.lock
ecdsa/src/der.rs
ecdsa/src/verify.rs

Updates `elliptic-curve` crates as well as `der`, `pkcs8`, and `spki` to the latest upstream commits

ecdsa: bump `elliptic-curve` + formats crates

---

Cargo.lock
ecdsa/src/sign.rs
ecdsa/src/verify.rs
ed25519/src/pkcs8.rs

Updates to the latest git version of the `pkcs8` crate, which uses `TryFrom` to handle the final step of decoding keys

Update `pkcs8` crate

---

Cargo.lock
Cargo.toml

Removes the git-based dependencies

Use released RustCrypto/formats crates

---

ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/recovery.rs

Previously `RecoverableSignPrimitive` would return a 1-bit flag to use as the "recid".
While this suffices for the only current use case of this crate, which is secp256k1, it doesn't for other curves, where there is a practical possibility that an affine coordinate (i.e. element of the base field) might overflow the curve's order, i.e. that it won't be a valid element of the scalar field.
This commit adds a 0-3 valued `RecoveryId` type which captures all cases, and uses it as the return value for `RecoverableSignPrimitive`. This provides a cross-curve compatible type for the recovery ID, which can be used in a generic implementation of ECDSA (forthcoming).

ecdsa: add `RecoveryId` type

---

Cargo.lock
ecdsa/src/lib.rs

The available curve arithmetic is now expressive enough that it's possible to implement `Signature::normalize_s` generically for all curves with a `ScalarArithmetic` backend.
Because of that, we no longer need a special "helper trait" for this purpose, and so `NormalizeLow` can be removed.

ecdsa: remove `NormalizeLow` trait

---

ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/sign.rs

Consolidates `RecoverableSignPrimitive` into `SignPrimitive`.
These traits were nearly identical. This commit combines them into a single trait that works in all use cases.

ecdsa: remove `RecoverableSignPrimitive`

---

Cargo.lock
ecdsa/src/hazmat.rs
ecdsa/src/sign.rs

Leverages the newly added `AffineXCoordinate` trait from RustCrypto/traits#817 to provide a default generic implementation of the ECDSA signature algorithm.
Downstream crates can choose to override this implementation if they so desire, allowing them to potentially leverage more efficient arithmetic.
This approach does have a disadvantage that it necessarily adds a `ScalarArithmetic<Scalar = Self>` bound on the curve, meaning that `SignPrimitive` can only be impl'd for a particular curve's scalar type, as opposed to the original design goal of allowing it to be impl'd for a hardware ECDSA accelerator that stores a private scalar.
Either the default impl needs to be replaced with a blanket impl with more restrictive bounds, or a separate trait needs to be added to support hardware …

Add default impl of `SignPrimitive::try_sign_prehashed`

---

ecdsa/src/hazmat.rs
ecdsa/src/verify.rs

Similar to #396, this adds a generic implementation of ECDSA signature verification by providing a default implementation of the `VerifyPrimitive::verify_prehashed` method.
Downstream crates can choose to override this implementation if they so desire, allowing them to potentially leverage more efficient arithmetic such as Shamir's trick / linear combinations (at least, until such a time as there are traits for these in the `group` crate).
This approach does have a disadvantage that it necessarily adds a `AffineArithmetic<AffinePoint = Self>` bound on the curve, meaning that `VerifyPrimitive` can only be impl'd for a particular curve's affine point type, as opposed to the original design goal of allowing it to be impl'd for a hardware ECDSA accelerator that stores a private scalar.
Either …

ecdsa: add default generic impl of `VerifyPrimitive::verify_prehashed`

---

Cargo.lock
ed25519/Cargo.toml
ed25519/src/lib.rs
ed25519/src/pkcs8.rs

When `pkcs8` + `zeroize` is enabled, uses `zeroize` as part of the `Drop` impl for the `KeypairBytes` type.

ed25519: `zeroize` feature + doc improvements

---

ed25519/Cargo.toml
ed25519/src/lib.rs
ed25519/src/pkcs8.rs

Adds a `Signature::from_bytes` inherent method which matches the method of the same name on the `Signature` trait, i.e. it returns a `signature::Result`.
This method performs a partial range check on the `s` component of the signature to ensure fit within the order of ~2^(252.5). It won't reject all invalid signatures, but it will detect quite a few of them.
Deprecates the infallible `Signature::new` method, since it can't detect invalid signatures. While the `from_bytes` method isn't perfect, it can be improved in the future, whereas an infallible method can't.

ed25519: deprecate `Signature::new` in favor of `::from_bytes`

---

ed25519/src/lib.rs
ed25519/tests/hex.rs

Adds support for serializing and deserializing Ed25519 signatures from hexadecimal using standard `core::{fmt, str}` traits.

ed25519: impl `Display`/`LowerHex`/`UpperHex`/`FromStr` for `Signature`

---

ed25519/README.md
ed25519/src/lib.rs

This changes the now-deprecated `Signature::new` method as well as the `From<[u8; 64]>` impl on `Signature` to use `Signature::from_bytes` and panics if the signature is invalid.

ed25519: enforce signature invariants

---

Cargo.lock
ed25519/CHANGELOG.md
ed25519/Cargo.toml
ed25519/src/lib.rs

- `Signature::BYTE_SIZE` constant ([#380])
- PKCS#8 support via `KeypairBytes` type ([#381])
- `zeroize` feature ([#400])
- Impl `Display`/`LowerHex`/`UpperHex`/`FromStr` for `Signature` ([#402])
- Deprecate `SIGNATURE_LENGTH` constant in favor of `Signature::BYTE_SIZE` ([#380])
- Deprecate `Signature::new` in favor of `Signature::from_bytes`/`TryFrom` ([#401])
- `Signature::new` now panics on invalid signatures ([#403])
[#380]: https://github.com/RustCrypto/signatures/pull/380
[#381]: https://github.com/RustCrypto/signatures/pull/381
[#400]: https://github.com/RustCrypto/signatures/pull/400
[#401]: https://github.com/RustCrypto/signatures/pull/401
[#402]: https://github.com/RustCrypto/signatures/pull/402
[#403]: https://github.com/RustCrypto/signatures/pull/403

ed25519 v1.3.0

---

.github/workflows/ecdsa.yml
ecdsa/src/lib.rs

There are various feature combinations around `serde` which weren't working.
This commit fixes those combinations, adds TODOs to eventually simplify the feature combinations so they aren't needed, and adds CI to ensure it builds with all feature combinations.

ecdsa: fix `serde` feature combos; improve CI

---

Cargo.lock
Cargo.toml
ecdsa/Cargo.toml
ecdsa/src/verify.rs

Also bumps the `der` crate dependency to v0.5

ecdsa: bump `elliptic-curve` dependency to v0.11

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs
ecdsa/src/verify.rs

- `RecoveryId` type ([#392])
- Default generic impl of `SignPrimitive::try_sign_prehashed` ([#396])
- Default generic impl of `VerifyPrimitive::verify_prehashed` ([#397])
- `serde` support ([#406])
- Make `Signature::normalize_s` non-mutating ([#355])
- Switch from `ScalarBytes<C>` to `ScalarCore<C>` ([#356])
- Use `PrimeCurve` trait ([#357])
- Replace `FromDigest` trait with `Reduce` ([#372])
- 2021 edition upgrade; MSRV 1.56 ([#384])
- Allow `signature` v1.4 as a dependency ([#385])
- Bump `der` dependency to v0.5 ([#408])
- Bump `elliptic-curve` dependency to v0.11 ([#408])
- Split out `rfc6979` crate ([#409])
- `NormalizeLow` trait ([#393])
- `RecoverableSignPrimitive` ([#394])
[#355]: https://github.com/RustCrypto/signatures/pull/355
[#356]: …

ecdsa v0.13.0

---

Cargo.lock
ed25519/Cargo.toml
ed25519/README.md
ed25519/src/lib.rs
ed25519/src/pkcs8.rs
ed25519/tests/serde.rs

Upgrades the Rust edition used by this crate to the latest available

ed25519: Rust 2021 edition upgrade

---

ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/sign.rs

Adds a function for computing RFC6979's `k` generation algorithm specific to the ECDSA use case, i.e. handling type conversions prior to calling the `rfc6979` crate's implementation.

ecdsa: add `hazmat::rfc6979_generate_k` function

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/hazmat.rs
ecdsa/src/verify.rs

Use the trait introduced in RustCrypto/traits#833 to implement ECDSA verification.

ecdsa: use `LinearCombination` trait

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Use `LinearCombination` trait ([#417])
[#417]: https://github.com/RustCrypto/signatures/pull/417

ecdsa v0.13.2

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- Use revised `LinearCombination` trait ([#419])
[#419]: https://github.com/RustCrypto/signatures/pull/419

ecdsa v0.13.3

---

ecdsa/src/lib.rs
ed25519/src/lib.rs

I found myself in need of a `to_vec` method and thought it would be convenient to add.
It can be written today as `sig.as_ref().to_vec()` but having a dedicated method is more ergonomic.

ecdsa+ed25519: add `Signature::to_vec`

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs

- `Signature::to_vec` ([#428])
[#428]: https://github.com/RustCrypto/signatures/pull/428

ecdsa v0.13.4

---

ed25519/README.md

This is primarily to note that PKCS#8 support is exempted from SemVer and minor version updates to the `ed25519` crate may require an accompanying upgrade to the `pkcs8` crate.
Downstream dependencies who wish to avoid breakages should lock to a particular minor version.

ed25519: add SemVer policy

---

.github/workflows/ecdsa.yml
.github/workflows/rfc6979.yml

It was previously missing one, and only vicariously tested via the `ecdsa` crate.

rfc6979: add CI workflow

---

ecdsa/Cargo.toml

The `elliptic-curve` crate was pinned to inconsistent versions, and without the `=` predicate.
It should still resolve to the correct version for now. This fixes the inconsistency and pins it directly to specific prerelease versions.

ecdsa: fix prerelease version pinning

---

Cargo.lock
ed25519/CHANGELOG.md
ed25519/Cargo.toml
ed25519/README.md
ed25519/src/lib.rs

NOTE: This crate now requires **Rust 1.56** at a minimum as the Rust edition has been upgraded to 2021.
Previous 1.x releases of this crate supported an MSRV of 1.47. If you would like to use this crate with earlier releases of Rust, add the following version constraint in your project's Cargo.toml to constrain it to the supported version range:
```toml
[dependencies]
ed25519 = ">=1, <1.4" # ed25519 1.4 requires MSRV 1.56
```
Note that is our policy that we may change the MSRV in the future, but it will
be accompanied by a minor version bump.
- `Signature::to_vec` ([#428])
- Rust 2021 edition upgrade ([#412])
[#412]: https://github.com/RustCrypto/signatures/pull/412
[#428]: https://github.com/RustCrypto/signatures/pull/428

ed25519 v1.4.0

---

ecdsa/LICENSE-APACHE
ecdsa/LICENSE-MIT
ed25519/LICENSE-APACHE
ed25519/LICENSE-MIT
rfc6979/LICENSE-APACHE
rfc6979/LICENSE-MIT

It's conventional, and helpful for tooling, to include copies of licenses in your project.  The README is clear that this project is licensed under either of MIT or Apache licenses, so those are the two I've added.
In the copyright statements I've used "RustCrypto/signatures authors" and "2018" (which seems to be when the first commit was).
If you think this is a sensible idea but have a healthy paranoia about whether strangers on the internet can be trusted to provide license files, you might prefer to reject this MR and achieve the same end by using the github helper https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Add license files

---

ecdsa/src/verify.rs

Adds a thunk to `PublicKey::from_affine` for initializing a `VerifyingKey` from an affine point.
The method is fallible because the identity (a.k.a. point at infinity) is disallowed as a verifying key.

ecdsa: add `VerifyingKey::from_affine`

---

ed25519/src/lib.rs

The documentation previously referred to these two defunct projects

ed25519: remove `signatory` and `sodiumoxide` references

---

ecdsa/src/hazmat.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Changes `SignPrimitive` and `VerifyPrimitive` to accept `FieldBytes<C>` rather than `Scalar<C>`, performing a reduction internally.
Also refactors the `hazmat::rfc6979_generate_k` free function as a method of `SignPrimitive`, i.e.:
```
SignPrimitive::try_sign_prehashed_rfc6979
```

ecdsa: have primitive methods accept field bytes + RFC6979 API

---

ecdsa/src/dev.rs

Updated with the breaking changes to the `SignPrimitive` and `VerifyPrimitive` macros.

ecdsa: fix test generator macros in `dev` module

---

Cargo.lock
ecdsa/Cargo.toml

Also cuts a v0.14.0-pre.5 prerelease of `ecdsa`

ecdsa: bump `elliptic-curve` dependency to v0.12.0-pre.4

---

Cargo.lock
ecdsa/Cargo.toml
rfc6979/CHANGELOG.md
rfc6979/Cargo.toml
rfc6979/src/lib.rs

- License files ([#447])
- Bump `hmac` dependency to v0.12 ([#433])
- Bump `crypto-bigint` dependency to v0.4 ([#469])
[#433]: https://github.com/RustCrypto/signatures/pull/433
[#447]: https://github.com/RustCrypto/signatures/pull/447
[#469]: https://github.com/RustCrypto/signatures/pull/469

rfc6979 v0.2.0

---

ecdsa/src/hazmat.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Adds primitive methods that operate on a generic `D` digest algorithm implementation.
This simplifies invoking the primitive methods.

ecdsa: add `try_sign_digest_rfc6979` and `verify_digest` primitives

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- `SignPrimitive::try_sign_digest_rfc6979` ([#475])
- `VerifyPrimitive::verify_digest` ([#475])
[#475]: https://github.com/RustCrypto/signatures/pull/475

ecdsa v0.14.1

---

ed25519/src/lib.rs

Parses byte array parsed from `serde` deserializer using `TryInto`, which avoids potential panics.
Closes #478

ed25519: use `TryInto` in `serde` deserializers

---

Cargo.lock
ed25519/CHANGELOG.md
ed25519/Cargo.toml

- Use `TryInto` in `serde` deserializers ([#479])
[#479]: https://github.com/RustCrypto/signatures/pull/479

ed25519 v1.5.1

---

Cargo.lock
ed25519/CHANGELOG.md
ed25519/Cargo.toml

- Overflow handling in `serde` deserializers ([#482])
[#482]: https://github.com/RustCrypto/signatures/pull/482

ed25519 v1.5.2

---

Cargo.toml
dsa/Cargo.toml
dsa/src/sig.rs
ecdsa/Cargo.toml

- add description to Cargo.toml
- minor DER signature fixup
- set `opt-level = 2` at workspace level so tests run fast by default

dsa: description and boilerplate fixups

---

dsa/examples/export.rs
dsa/examples/generate.rs
dsa/examples/sign.rs
dsa/src/generate/keypair.rs
dsa/src/generate/secret_number.rs
dsa/src/lib.rs
dsa/src/signing_key.rs
dsa/src/verifying_key.rs
dsa/tests/deterministic.rs
dsa/tests/private_key.rs
dsa/tests/public_key.rs
dsa/tests/signature.rs

For consistency with the `ecdsa` crate: see [`ecdsa::SigningKey`](https://docs.rs/ecdsa/latest/ecdsa/struct.SigningKey.html) and [`ecdsa::VerifyingKey`](https://docs.rs/ecdsa/latest/ecdsa/struct.VerifyingKey.html).
This naming scheme follows the philosophy that in a digital signature scheme, it's clearer to name keys after their roles.
DSA admittedly benefits less than other schemes where there are other potential algorithms that can be implemented using the same core mathematics which share the same key representations.
cc @aumetra

dsa: rename key types to `SigningKey` and `VerifyingKey`

---

dsa/README.md
ecdsa/README.md

Note that neither crate has been audited by a third party, and that there may potentially be timing variabilities or other sidechannels in the implementations.

dsa+ecdsa: add security warnings to README.md(s)

---

Cargo.lock
dsa/CHANGELOG.md
dsa/Cargo.toml

- Internal sanity check validating the `r` and `s` components of the signature ([#489])
- Public `OID` constant representing the object identifier defined in RFC3279 § 2.3.2 ([#489]) 
- `Components::generate` now takes an `KeySize` struct instead of an `(u32, u3e2)` tuple ([#489])
- `Components::from_components`, `SigningKey::from_components` and `VerifyingKey::from_components` are now fallible and validate themselves upon creation ([#489])
- `is_valid` methods on `Components`, `SigningKey` and `VerifyingKey`: constructor now ensures that invalid forms are unrepresentable ([#489])
[#489]: https://github.com/RustCrypto/signatures/pull/489

dsa v0.3.0

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml
ecdsa/README.md

- Security warning in README.md ([#486])
- Use `serdect` for `Signature` types ([#497])
[#486]: https://github.com/RustCrypto/signatures/pull/486
[#497]: https://github.com/RustCrypto/signatures/pull/497

ecdsa v0.14.2

---

Cargo.lock
dsa/Cargo.toml
dsa/src/generate/secret_number.rs
dsa/src/signing_key.rs
dsa/tests/deterministic.rs
ecdsa/Cargo.toml
ecdsa/src/hazmat.rs
ecdsa/src/sign.rs
rfc6979/Cargo.toml
rfc6979/src/lib.rs

`SimpleHmac` allows for significantly simpler bounds on generic digest types versus `Hmac`.

rfc6979: use `SimpleHmac` to implement `HmacDrbg`

---

Cargo.lock
dsa/Cargo.toml
ecdsa/Cargo.toml
rfc6979/CHANGELOG.md
rfc6979/Cargo.toml

- Use `SimpleHmac` to implement `HmacDrbg` ([#499])
[#499]: https://github.com/RustCrypto/signatures/pull/499

rfc6979 v0.3.0

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- Simplified digest trait bounds ([#499])
- Bump `rfc6979` dependency to v0.3 ([#500])
[#499]: https://github.com/RustCrypto/signatures/pull/499
[#500]: https://github.com/RustCrypto/signatures/pull/500

ecdsa v0.14.3

---

ecdsa/Cargo.toml

Tightens the version requirement of the `signature` crate to `>= 1.5, < 1.6` (same as the `dsa` crate) to avoid a potential semver breakage.
Closes #507

Tighten `signature` version requirement of `ecdsa` crate

---

ecdsa/src/sign.rs

`ecdsa` depends on `elliptic-curve` 0.12, which depends on `zeroize` 1.5, so the trait should be safe to use.

ecdsa: add `ZeroizeOnDrop` marker for `SigningKey`

---

ecdsa/Cargo.toml

This release is now out and compatible with the versions of `digest` and `rand_core` that `ecdsa` uses.

ecdsa: allow `signature` v1.6

---

Cargo.lock
dsa/CHANGELOG.md
dsa/Cargo.toml

- Bump `rfc6979` to v0.3 ([#500])
- Allow `signature` v1.6 ([#513])
[#500]: https://github.com/RustCrypto/signatures/pull/500
[#513]: https://github.com/RustCrypto/signatures/pull/513

dsa v0.4.0

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- Impl `EncodePublicKey` for `VerifyingKey` ([#505])
- ZeroizeOnDrop marker for SigningKey ([#509])
- Restrict `signature` version to v1.5-v1.6 ([#508], [#512])
[#505]: https://github.com/RustCrypto/signatures/pull/505
[#508]: https://github.com/RustCrypto/signatures/pull/508
[#509]: https://github.com/RustCrypto/signatures/pull/509
[#512]: https://github.com/RustCrypto/signatures/pull/512

ecdsa v0.14.4

---

ecdsa/src/sign.rs

ecdsa: Implement `EncodePrivateKey` for `SigningKey`

---

ed25519/Cargo.toml

The `ed25519` crate fails to compile with only the `pem` feature flag since the current implementation depends on the `alloc` crate (via `alloc::string::{String, ToString}`).
The `pkcs8`'s `pem` feature already depends on the `alloc` crate anyway, so enabling the `ed25519`'s `alloc` feature together with the `pem` feature should be fine.

ed25519: Fix compilation of `pem` feature

---

.github/workflows/ed25519.yml

It wasn't tested before. See #524.

ed25519: CI test for build with `pem` feature alone

---

ecdsa/src/sign.rs
ecdsa/src/verify.rs

Adds borrowing accessors for the inner `NonZeroScalar` and `AffinePoint` within `SigningKey` and `VerifyingKey` respectively.
These mirror the corresponding inherent methods on `SecretKey` and `PublicKey` as defined in the `elliptic-curve` crate.

ecdsa: add `SigningKey::as_nonzero_scalar`/`VerifyingKey::as_affine`

---

ecdsa/src/recovery.rs

They're trivial and potentially useful for defining constants

ecdsa: make `RecoveryId` methods `const fn`

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- Impl `EncodePrivateKey` for `SigningKey` ([#523])
- `SigningKey::as_nonzero_scalar` ([#528])
- `VerifyingKey::as_affine` ([#528])
- `RecoveryId::from_byte` ([#531])
- Make `RecoveryId` methods `const fn` ([#529])
[#523]: https://github.com/RustCrypto/signatures/pull/523
[#528]: https://github.com/RustCrypto/signatures/pull/528
[#529]: https://github.com/RustCrypto/signatures/pull/529
[#531]: https://github.com/RustCrypto/signatures/pull/531

ecdsa v0.14.5

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/hazmat.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Adds "hazmat" trait impls to `SigningKey` and `VerifyingKey` respectively which allow computing signatures over raw message digests. See RustCrypto/traits#1099.
The implementation allows digests which are shorter or longer than the field size of the curve, using zero-padding if the digest is too short, and truncating if it's too long. The minimum digest size is set to half of the curve's field size.

ecdsa: impl `signature::hazmat::{PrehashSigner, PrehashVerifier}`

---

ecdsa/src/sign.rs
ecdsa/src/verify.rs

This trait describes the relationship between signing and verifying keys, allowing the latter to be accessed from the former in a trait-based manner.

ecdsa: impl `Keypair` for `SigningKey`

---

.github/workflows/ecdsa.yml
ecdsa/src/sign.rs

Uses automatic permutation test rather than hardcoded combinations

ecdsa: use `cargo hack` in CI to test feature combos

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- Impl `signature::hazmat::{PrehashSigner, PrehashVerifier}` ([#534])
- Impl `signature::Keypair` for `SigningKey` ([#535])
[#534]: https://github.com/RustCrypto/signatures/pull/534
[#535]: https://github.com/RustCrypto/signatures/pull/535

ecdsa v0.14.6

---

ecdsa/Cargo.toml
ecdsa/src/sign.rs

Following RustCrypto/traits#1107 this relaxes the trait bounds to the minimum requirements.

ecdsa: relax `Keypair` bounds

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- Relax `Keypair` bounds ([#539])
[#539]: https://github.com/RustCrypto/signatures/pull/539

ecdsa v0.14.7

---

ecdsa/src/hazmat.rs

This is a fix for the issue I mentioned at https://github.com/RustCrypto/signatures/pull/534#discussion_r980613066. I believe the present implementation of `prehash_to_field_bytes` can't interop with OpenSSL (at least but should be the same for other crypto libraries)...
`prehash_to_field_bytes` was zero-padding on the right of the byte sequence but this must be done on the left because the output is evaluated as a integer encoded in big-endian, and its integer representation should be stable regardless of sequence length.
This behavior is defined on various documents including RFC6979 Section 2.3.2., SEC 1 Section 2.3.8., NIST FIPS 186-4 Appendix C.2.1.
- https://datatracker.ietf.org/doc/html/rfc6979#section-2.3.2 
- https://www.secg.org/sec1-v2.pdf
- …

ecdsa: prehash must receive zero-pads on left

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- Impl `From<SigningKey>` for `SecretKey` ([#548])
- Prehash must receive zero-pads on left ([#547])
[#547]: https://github.com/RustCrypto/signatures/pull/547
[#548]: https://github.com/RustCrypto/signatures/pull/548

ecdsa v0.14.8

---

.github/dependabot.yml

Extend Dependabot configuration to automatically open PRs for outdated actions.
Inspired by https://github.com/RustCrypto/hashes/pull/410#issuecomment-1252658128.

chore: extend Dependabot configuration for GitHub Actions updates

---

dsa/src/lib.rs

It's part of the public API.
The `rsa` crate provides a similar re-export.

dsa: re-export `BigUint`

---

dsa/Cargo.toml
dsa/src/signing_key.rs
dsa/src/verifying_key.rs

Expose the ability for the user to provide a prehashed hash-value for signing/verification. In rare cases, this is needed in other protocols. I have attempted to solve this with a custom Digest implementation, but eventually ran into (forced) finalization which affects the hash value.

dsa: expose signing and verifying of prehashed hash value

---

dsa/src/signing_key.rs
dsa/src/verifying_key.rs
dsa/tests/signature.rs

In follow-up of discussion in #520: a minimal implementation for `Signer` and `Verifier` using SHA-256 for digests. The issue discusses possible options of introducing the OID, however this is not part of this implementation.

dsa: implement `Signer` and `Verifier` using SHA-256 as default

---

Cargo.lock
dsa/CHANGELOG.md
dsa/Cargo.toml

- Expose signing and verifying of prehashed hash value ([#558])
- Implement `Signer` and `Verifier` using SHA-256 as default ([#559])
[#558]: https://github.com/RustCrypto/signatures/pull/558
[#559]: https://github.com/RustCrypto/signatures/pull/559

dsa v0.4.2

---

Cargo.lock
dsa/Cargo.toml
dsa/examples/sign.rs
dsa/src/sig.rs
dsa/src/signing_key.rs
dsa/src/verifying_key.rs
dsa/tests/deterministic.rs
ecdsa/Cargo.toml
ecdsa/src/der.rs
ecdsa/src/lib.rs
ecdsa/src/sign.rs
ed25519/Cargo.toml
ed25519/src/lib.rs

Implements the proposed breaking changes to the `signature` crate from https://github.com/RustCrypto/traits/pull/1141
Most notably the `Signature` trait has been replaced with a `SignatureEncoding` trait which permits an internally structured signature representation.

Bump `signature` to 2.0.0-pre

---

ed25519/src/lib.rs

The v1.0 release of `ed25519` included infallible conversions from `[u8; 64]`, however that was retroactively changed to reject signatures which overflowed the field modulus, so those methods were deprecated and changed to panicking conversions.
Now that the crate is on v2.0.0-pre, we can remove those deprecated methods.
Closes #563.

ed25519: remove deprecated infallible conversions

---

ecdsa/src/lib.rs

Now that the `AsRef<[u8]>` bound on signatures has been removed, `ecdsa::Signature` can have a structured internal representation.

ecdsa: use `ScalarCore` for `r` and `s` components

---

ecdsa/src/sign.rs

The `SigningKey` is internally a keypair, so callers can borrow the `VerifyingKey`, rather than making a copy.

ecdsa: have `SigningKey::verifying_key` return a reference

---

ecdsa/src/hazmat.rs
ecdsa/src/sign.rs

RFC6979 is built on HMAC-DRBG which needs `BlockSizeUser` and `FixedOutputReset` bounds.
This change ensures that `DigestPrimitive::Digest` is always usable with RFC6979.

ecdsa: add bounds for RFC6979 to `DigestPrimitive::Digest`

---

ecdsa/src/der.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

This allows using these traits along with `SigningKey`/`VerifyingKey` to directly sign and verify `der::Signature`s.
cc @lumag

ecdsa: add `*Signer`/`*Verifier` impls for `der::Signature`

---

Cargo.lock
dsa/Cargo.toml
dsa/src/components.rs
dsa/src/lib.rs
dsa/src/signing_key.rs
dsa/src/verifying_key.rs

All of the `Debug` impls in this crate benefit from displaying something, including `SigningKey` which can display its associated `VerifyingKey`.
This commit switches to derived `Debug` for all types except `SigningKey`, where it displays the `verifying_key` field then uses `finish_non_exhaustive` to prevent displaying the secret component `x`.
They could probably benefit from some better formatting than what the derived implementation provides.

dsa: remove use of `opaque-debug`

---

ecdsa/src/hazmat.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

Removes the verbosely named `prehash_to_field_bytes` from the `DigestPrimitive` trait, chaning it to a `bits2field` free function which has a `C: PrimeCurve` generic parameter.
The name is inspired by `bits2int` from RFC6979, however it does not perform a reduction step.

ecdsa: refactor `prehash_to_field_bytes` to `bits2field` free func

---

ecdsa/src/recovery.rs

Initial support for recovering a `VerifyingKey` from a `RecoveryId` and a signature over one of the following:
- Message (i.e. bytestring) hashed using `DigestPrimitive::Digest`
- Message `Digest`
- Message prehash (i.e. output of a `Digest`)
Closes #525

ecdsa: initial `VerifyingKey` recovery support

---

ecdsa/src/recovery.rs
ecdsa/src/sign.rs
ecdsa/src/verify.rs

This functionality can be used to compute a `RecoveryId` from a verifying key, message, and signature, without having this information computed during signing time.
It uses a brute force method and is thus much slower than computing it at signing time.

ecdsa: add trial recovery functionality

---

ed25519/src/lib.rs
ed25519/src/pkcs8.rs

- Re-exports `pkcs8::PublicKeyBytes` at the toplevel
- Re-exports `pkcs8::PrivateKeyInfo` from the upstream crate

ed25519: re-export `PublicKeyBytes` and `pkcs8::PrivateKeyInfo`

---

ed25519/src/pkcs8.rs

They're needed to properly impl the `EncodePrivateKey`/`EncodePublicKey` traits.

ed25519: make `pkcs8::*Document` re-exports public

---

ed25519/src/lib.rs

Change Signature::from_bytes to take `[u8; 64]` as argument rather
than `&[u8]` which:
- provides consistency with KeypairBytes::from_bytes,
- encodes the length in type system allowing clients to assert length
at compile time and
- removes run-time length check.
At the same time, since there’s already TryFrom<&[u8]> implementation
for Signature, no features are lost and clients who want to create the
signature from a slice can do it via Signature::try_from.
This does change the API but since the crate is currently in 2.0
preview stage, that should be fine since API breaking changes are
allowed by symantic versioning at major version upgrade.

ed25519: change Signature::from_bytes to take sized array

---

ed25519/src/lib.rs
ed25519/src/serde.rs
ed25519/tests/hex.rs
ed25519/tests/serde.rs

Adds a `ComponentBytes` type alias for `[u8; 32]` and stores the `R` and `s` component signatures as separate byte arrays.
This allows for simple, infallible `ComponentBytes` accessors:
- `pub fn r_bytes(&self) -> &ComponentBytes`
- `pub fn s_bytes(&self) -> &ComponentBytes`

ed25519: store `R` and `s` components separately

---

ed25519/src/lib.rs

Add constructor which accepts the serialized `R` and `s` components as separate parameters, (partially) validating the `s` component.

ed25519: add `Signature::from_components`

---

ed25519/src/lib.rs

Uses the `TryFrom` trait to invoke `Signature::from_bytes`.

ed25519: impl `TryFrom<SignatureBytes>` for `Signature`

---

Cargo.lock
dsa/Cargo.toml
dsa/src/signing_key.rs
ecdsa/Cargo.toml
ecdsa/src/sign.rs
ed25519/Cargo.toml

This version moves back to `&mut impl CryptoRngCore` as the type signature for RNGs.
See RustCrypto/traits#1183

signature v2.0.0-rc.1

---

ecdsa/Cargo.toml
ecdsa/src/lib.rs
ecdsa/src/recovery.rs
ecdsa/src/signing.rs
ecdsa/src/verifying.rs

Corresponding to the module name changes in #609, this renames the crate feature names to match:
- `sign` => `signing`
- `verify` => `verifying`
This better matches the `SigningKey` and `VerifyingKey` type names.

ecdsa: rename `signing` and `verifying` features

---

Cargo.lock
dsa/Cargo.toml
ecdsa/Cargo.toml
ed25519/Cargo.toml

Release notes: https://github.com/RustCrypto/traits/pull/1211

Bump `signature` crate dependency to v2.0

---

ed25519/CHANGELOG.md

A backported fix was released in #616 which fixed a version requirement.
That branch won't be merged into `master`. However, this commit cherry picks just the CHANGELOG.md changes.
It also notes which releases were yanked because they had a broken
version requirement for `signature` >=1.3.1.

ed25519: add v1.5.3 release notes to CHANGELOG.md

---

Cargo.lock
dsa/CHANGELOG.md
dsa/Cargo.toml
dsa/LICENSE-MIT

- Use `&mut impl CryptoRngCore` ([#579])
- Bump `signature` crate dependency to v2.0 ([#614])
- Use of `opaque-debug` ([#572])
[#572]: https://github.com/RustCrypto/signatures/pull/572
[#579]: https://github.com/RustCrypto/signatures/pull/579
[#614]: https://github.com/RustCrypto/signatures/pull/614

dsa v0.5.0

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- `DigestPrimitive::Digest` now has bounds that work with RFC6979 ([#568])
- `*Signer`/`*Verifier` impls for `der::Signature` ([#569])
- `VerifyingKey` recovery support ([#576])
- Trial recovery support ([#580])
- Signature now internally structured with `r` and `s` components ([#565])
- `SigningKey::verifying_key` now returns a reference ([#567])
- Refactor `prehash_to_field_bytes` to `bits2field` free function ([#574])
- Rename `sign` feature to `signing` ([#610])
- Rename `verify` feature to `verifying` features ([#610])
- Bump `signature` crate dependency to v2.0 ([#614])
[#565]: https://github.com/RustCrypto/signatures/pull/565
[#567]: https://github.com/RustCrypto/signatures/pull/567
[#574]: https://github.com/RustCrypto/signatures/pull/574
[#580]: …

ecdsa v0.15.0

---

ed25519/src/hex.rs
ed25519/src/lib.rs

Note: should probably be replaced with `base16ct` as an optional dependency, but this is a quick cleanup.

ed25519: factor out `hex` module

---

Cargo.lock
ed25519/CHANGELOG.md
ed25519/Cargo.toml

- `pkcs8` re-exports ([#589], [#590], [#591], [#592])
- `Signature::from_components` method ([#600])
- Impl `TryFrom<SignatureBytes>` for `Signature` ([#601])
- Use `PublicKeyBytes` as `KeypairBytes::public_key` ([#570])
- `Signature::from_bytes` takes `SignatureBytes` as an argument ([#593])
- Store `R` and `s` components separately ([#595])
- Bump `signature` crate dependency to v2.0 ([#614])
- Deprecated `From<[u8; 64]>` conversion for signature ([#564])
- `AsRef<[u8]>` impl on `signature` ([#595])
[#564]: https://github.com/RustCrypto/signatures/pull/564
[#570]: https://github.com/RustCrypto/signatures/pull/570
[#589]: https://github.com/RustCrypto/signatures/pull/589
[#590]: https://github.com/RustCrypto/signatures/pull/590
[#591]: https://github.com/RustCrypto/signatures/pull/591 …

ed25519 v2.0.0

---

ed25519/src/lib.rs
ed25519/src/serde.rs
ed25519/tests/hex.rs

We've had a couple request to make signature parsing infallible. Presently it checks that the `s` scalar component of the signature has its three highest bits clear, which will reject some but not all signatures where `s` overflows the curve's order.
However, this check will not reject *all* such invalid signatures (at least as presently implemented), and the same check will be performed at the time the signature is verified (which *will* reject all such invalid signatures).
Though we already shipped `ed25519` v2.0.0 and this is a breaking change, that release has been yanked so we can get this change in last minute.

ed25519: infallible signature parsing

---

Cargo.lock
ed25519/CHANGELOG.md
ed25519/Cargo.toml
ed25519/src/lib.rs

- Make `Signature` parsing infallible ([#623])
[#623]: https://github.com/RustCrypto/signatures/pull/623

ed25519 v2.0.1

---

ed25519/Cargo.toml

The tested MSRV is 1.57, not 1.56.
It's correctly noted in the crate's README.md.

ed25519: fix `rust-version` in Cargo.toml

---

ed25519/src/lib.rs

The code is otherwise duplicated

ed25519: have `TryFrom<&[u8]>` call `Signature::from_slice`

---

Cargo.lock
ed25519/CHANGELOG.md
ed25519/Cargo.toml
ed25519/LICENSE-MIT

- Use namespaced features for `serde_bytes`; MSRV 1.60 ([#628])
[#628]: https://github.com/RustCrypto/signatures/pull/628

ed25519 v2.1.0

---

ecdsa/src/hazmat.rs
ecdsa/src/signing.rs
ecdsa/src/verifying.rs

Uses `C::Digest` unilaterally as the digest function to instantiate HMAC-DRBG for RFC6979. This replaces the previous inconsistent usage where sometimes `C::Digest` was used while in `DigestSigner` the generic `D` parameter was used.
With this, the various trait impls can be composed one in terms of the other:
`*Signer` -> `*DigestSigner` -> `*PrehashSigner`
This commit also removes `SignPrimitive::try_sign_digest_rfc6979` as the `*PrehashSigner` impls are now the only caller into `SignPrimitive` and the `DigestSigner` impls handle hashing.

ecdsa: refactor RFC6979 usage and trait impls

---

ecdsa/src/recovery.rs
ecdsa/src/verifying.rs

Adds methods which return the `RecoveryId` along with the signature, now that the generic implementation can compute them.

ecdsa: add `SigningKey::*_recoverable` methods

---

ecdsa/src/recovery.rs
ecdsa/src/signing.rs

Allows computing recoverable signatures using the `*Signer` traits, using a 2-tuple of `Signature` and `RecoveryId`.

ecdsa: add `*Signer` impls that return `RecoveryId`

---

.github/workflows/security-audit.yml
Cargo.lock
ecdsa/src/hazmat.rs
ecdsa/src/recovery.rs
ecdsa/src/signing.rs
rfc6979/Cargo.toml
rfc6979/src/ct_cmp.rs
rfc6979/src/lib.rs

The previous approach complicates supporting ECDSA with `FieldSize` which is different from `C::Uint::ByteSize`.
The new implementation eliminates `crypto-bigint` as a dependency and makes the API entirely byte-oriented.
This is a simpler approach which also eliminates some previous trait bounds on the generic ECDSA implementation.

rfc6979: decouple from `crypto-bigint`

---

Cargo.lock
Cargo.toml
ecdsa/Cargo.toml
ecdsa/src/der.rs
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/recovery.rs
ecdsa/src/signing.rs
ecdsa/src/verifying.rs

Bumps the `elliptic-curve` crate to the latest prerelease on crates.io.
Notably this includes changes to how `FieldBytes` is encoded made with the goal of supporting elliptic curves with unusual moduli such as P-224 and P-521:
https://github.com/RustCrypto/traits/pull/1220

ecdsa: bump `elliptic-curve` to v0.13.0-pre.1

---

ecdsa/src/dev.rs
ecdsa/src/hazmat.rs
ecdsa/src/recovery.rs
ecdsa/src/signing.rs
ecdsa/src/verifying.rs

Always borrow the input field bytes.
Fix test macros in the `dev` module.

ecdsa: use `&FieldBytes<C>` consistently; fix tests

---

Cargo.lock
Cargo.toml
ecdsa/src/hazmat.rs
ecdsa/src/recovery.rs
ecdsa/src/signing.rs
ecdsa/src/verifying.rs

Uses the newly (re)introduced method for reducing an input with serialized bytes to perform modular reductions on `FieldBytes`.
See: https://github.com/RustCrypto/traits/pull/1229

ecdsa: use `Reduce::reduce_bytes`

---

ecdsa/src/hazmat.rs

This eliminates a usage of `C::encode_field_bytes`.

ecdsa: use `FromUintUnchecked` for serializing order

---

ecdsa/src/hazmat.rs

This reverts commit 298129cbce828ade61241954eae25d6b7fafe9c6.
Abusing `from_uint_unchecked` for this broke `p384`, which appears to be serializing the order as zero causing an infinite loop when computing RFC6979.
Curiously, this didn't impact `p256`.

Revert "ecdsa: use `FromUintUnchecked` for serializing order (#644)"

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/hazmat.rs

Bumps `elliptic-curve` to v0.13.0-pre.3, and uses the new `FieldBytesEncoding` API.
This is needed to pass the curve's order to the RFC6979 implementation.

ecdsa: use `FieldBytesEncoding` to serialize `C::ORDER`

---

Cargo.lock
Cargo.toml
ecdsa/src/hazmat.rs

Switches to the newly consolidated `AffineCoordinates` trait.
See RustCrypto/traits#1237

ecdsa: use `AffineCoordinates` trait

---

Cargo.lock
Cargo.toml
ecdsa/Cargo.toml
ecdsa/src/hazmat.rs

Variable-time inversions can be faster than constant-time inversions and are fine in the context of verification.

ecdsa: use `Scalar::invert_vartime` for verification

---

Cargo.lock
Cargo.toml
ecdsa/src/hazmat.rs

Previously this was handled by a blanket impl for `ff::Field`, but that precludes curves being able to impl `invert_vartime`.
See also: https://github.com/RustCrypto/traits/pull/1242

ecdsa: add `Invert` bound

---

.github/workflows/ecdsa.yml
Cargo.lock
ecdsa/Cargo.toml
ecdsa/README.md
ecdsa/src/der.rs
ecdsa/src/signing.rs
ecdsa/src/verifying.rs

ecdsa: bump `elliptic-curve` to v0.13.0-rc.0

---

Cargo.lock
dsa/Cargo.toml
ecdsa/Cargo.toml
rfc6979/CHANGELOG.md
rfc6979/Cargo.toml

- MSRV 1.60 ([#628])
- Decouple from `crypto-bigint` ([#639])
[#628]: https://github.com/RustCrypto/signatures/pull/628
[#639]: https://github.com/RustCrypto/signatures/pull/639

rfc6979 v0.4.0

---

Cargo.lock
ecdsa/Cargo.toml

Release notes: https://github.com/RustCrypto/traits/pull/1255

ecdsa: bump `elliptic-curve` dependency to v0.13.0

---

Cargo.lock
dsa/CHANGELOG.md
dsa/Cargo.toml

- Bump `rfc6979` dependency to v0.4 ([#662])
- Bump `pkcs8` dependency to v0.10; MSRV 1.65 ([#664])
[#662]: https://github.com/RustCrypto/signatures/pull/662
[#664]: https://github.com/RustCrypto/signatures/pull/664

dsa v0.6.0

---

ecdsa/CHANGELOG.md

- `Decode` and `Encode` impls for `der::Signature` ([#666])
- Use `Scalar::invert_vartime` for faster verification ([#651])
- Bump `serdect` dependency to 0.2 ([#657])
- Bump `elliptic-curve` dependency to v0.13; MSRV 1.65 ([#660], [#663])
- Bump `rfc6979` dependency to v0.4 ([#662])
[#651]: https://github.com/RustCrypto/signatures/pull/651
[#657]: https://github.com/RustCrypto/signatures/pull/657
[#660]: https://github.com/RustCrypto/signatures/pull/660
[#662]: https://github.com/RustCrypto/signatures/pull/662
[#663]: https://github.com/RustCrypto/signatures/pull/663
[#666]: https://github.com/RustCrypto/signatures/pull/666

ecdsa v0.16.0

---

Cargo.lock
ed25519/CHANGELOG.md
ed25519/Cargo.toml

- Bump `pkcs8` dependency to v0.10 ([#665])
[#665]: https://github.com/RustCrypto/signatures/pull/665

ed25519 v2.2.0

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/verifying.rs

Adds an inherent method, gated on `alloc`, for serializing a `VerifyingKey` as a boxed byte slice containing the key's SEC1 encoding.
Also adds `From` conversions for converting to
`sec1::{CompressedPoint, EncodedPoint}`.

ecdsa: add `VerifyingKey::to_sec1_bytes` + more conversions

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- `VerifyingKey::to_sec1_bytes` + more conversions ([#675])
[#675]: https://github.com/RustCrypto/signatures/pull/675

ecdsa v0.16.1

---

rfc6979/src/lib.rs

Section 10.1.2.3 of [SP 800-90A](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-90Ar1.pdf) describes the instantiation function and shows that this argument should be called `personalization_string`. `additional_data` is something provided during bit generation, so if used it should be provided to the `fill_bytes` function of this library.

Rename additional_data to personalization_string

---

ecdsa/src/hazmat.rs
ecdsa/src/recovery.rs

This PR handles the case where the x-coordinate of r is reduced mod N in both recoverable signing and public key recovery. The chance that the x is reduced during signing with a randomly chosen k is negligible, so the changes to the signing method could be omitted.
Closing #584

Handle the reduced x case in public key recovery

---

.github/workflows/dsa.yml
.github/workflows/ecdsa.yml
.github/workflows/ed25519.yml
.github/workflows/rfc6979.yml
.github/workflows/security-audit.yml
.github/workflows/workspace.yml

Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/RustCrypto/signatures/actions/runs/4457105883:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct …

Replace unmaintained actions-rs/* actions in CI workflows

---

Cargo.lock
Cargo.toml
ecdsa/Cargo.toml
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs

Adds support for obtaining the RFC5758 OIDs associated with the digest algorithm used to compute a signature by introducing a new `SignatureWithOid` type.
The OID for a particular signature is vicariously available via the newly introduced `spki::DynAssociatedAlgorithmIdentifier` trait, which provides a generic interface for applications like X.509 certificate building.
The OID can either be specified explicitly or inferred from a `Digest` type which also impls `AssociatedOid`.
cc @baloo @lumag

ecdsa: add RFC5758 OID support

---

Cargo.lock
ecdsa/src/signing.rs
ecdsa/src/verifying.rs

Propagates the `AssociatedAlgorithmIdentifier` from `Signature<C>` to `SigningKey<C>` and `VerifyingKey<C>`.
cc @baloo @lumag

ecdsa: impl `SignatureAlgorithmIdentifier`

---

ecdsa/src/lib.rs
ecdsa/src/signing.rs

Adds a signature type which is paramaterized by an RFC5758-defined OID identifying the variant of ECDSA used to produce the signature.
cc @baloo @lumag

ecdsa: add `SignatureWithOid`

---

ecdsa/Cargo.toml
ecdsa/src/verifying.rs

Gated under a newly added `sha2` feature.
This implementation dispatches based on RFC5758 OIDs, selecting the appropriate hash function to use at runtime based on the OID.
cc @baloo @lumag

ecdsa: add `SignatureWithOid` verification support

---

Cargo.lock
ed25519/CHANGELOG.md
ed25519/Cargo.toml

- Bump `ring-compat` dev-dependency to v0.7 ([#692])
- Bump `ed25519-dalek` to v2.0.0-rc.2 ([#693])
[#692]: https://github.com/RustCrypto/signatures/pull/692
[#693]: https://github.com/RustCrypto/signatures/pull/693

ed25519 v2.2.1

---

Cargo.lock
Cargo.toml
ecdsa/src/lib.rs

Return Result from algorithm_identifier().
Depends on https://github.com/RustCrypto/formats/pull/974

ecdsa: follow the DynAssociatedAlgorithmIdentifier changes

---

dsa/Cargo.toml
ecdsa/Cargo.toml

`signature` v2.1.0 is out and only adds features. It does not change the `digest` or `rand_core` dependencies (there are SemVer exceptions for these crates, hence the non-SemVer requirement)
Because those deps are unchanged in v2.1.0, we can relax the requirement to support v2.0 and v2.1 releases.

dsa+ecdsa: loosen `signature` bound to `2.0, <2.2`

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/signing.rs
ecdsa/src/verifying.rs

...from the `elliptic-curve` crate, as released in v0.13.3

ecdsa: forward `AssociatedAlgorithmIdentifier` impls

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- RFC5758 OID support ([#686])
- `SignatureAlgorithmIdentifier` impls for `SigningKey`/`VerifyingKey` ([#688])
- `SignatureWithOid` ([#689], [#690])
- `AssociatedAlgorithmIdentifier` impls for `SigningKey`/`VerifyingKey` ([#698])
- Loosen `signature` bound to `2.0, <2.2` ([#697])
[#686]: https://github.com/RustCrypto/signatures/pull/686
[#688]: https://github.com/RustCrypto/signatures/pull/688
[#689]: https://github.com/RustCrypto/signatures/pull/689
[#690]: https://github.com/RustCrypto/signatures/pull/690
[#697]: https://github.com/RustCrypto/signatures/pull/697
[#698]: https://github.com/RustCrypto/signatures/pull/698

ecdsa v0.16.3

---

Cargo.lock
dsa/CHANGELOG.md
dsa/Cargo.toml

- Loosen `signature` bound to `2.0, <2.2` ([#697])
[#697]: https://github.com/RustCrypto/signatures/pull/697

dsa v0.6.1

---

ecdsa/src/hazmat.rs

The implementation was adapted from `k256`, which produces signatures with low-S normalization.
However, the provided implementation does not low-S normalize signatures, so it should not be considered in the `RecoveryId` computation.

ecdsa: fix `RecoveryId` computation in `SignPrimitive`

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- `RecoveryId` computation in `SignPrimitive` ([#702])
[#702]: https://github.com/RustCrypto/signatures/pull/702

ecdsa v0.16.4

---

ecdsa/src/der.rs
ecdsa/src/dev.rs
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs

This is needed to make curves like P-224 and P-521 work, since the size of the `C::Uint` may not match the size of an integer serialization of a field element (since `C::Uint::MAX` may be much larger than the field modulus)

ecdsa: use `C::FieldBytesSize` over `C::Uint::BYTES`

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- Use `C::FieldBytesSize` instead of `C::Uint::BYTES` ([#705])
[#705]: https://github.com/RustCrypto/signatures/pull/705

ecdsa v0.16.5

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- Test macro handling of serialized field size ([#707])
[#707]: https://github.com/RustCrypto/signatures/pull/707

ecdsa v0.16.6

---

ecdsa/src/der.rs

Adds a reference to the ASN.1 schema and where it's defined

ecdsa: add RFC5480 citation for `der::Signature`

---

ecdsa/src/lib.rs

The width of a serialized `Signature` is generic and based on the size of the underlying curve's modulus, not a fixed 64-bytes.

ecdsa: `serde` doc fixup

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/der.rs

see https://github.com/RustCrypto/formats/pull/1047

ecdsa: Adds support for the `SignatureBitStringEncoding` trait

---

ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

Added
- RFC5480 citation for `der::Signature` (#710)
- support for the `SignatureBitStringEncoding` trait (#716)
Changed
- bump `elliptic-curve` from 0.13.3 to 0.13.4 (#709)
- `der::Signature` citation to RFC5912 (#711)
- make `fmt` impls more consistent (#713)
Fixed
- `serde` doc fixup (#712)

ecdsa: v0.16.7

---

ecdsa/src/hazmat.rs
ecdsa/src/lib.rs

Implements `from_bytes` in terms of `from_scalars`, rather than the other way around.
This places the logic for checking that `r` and `s` are nonzero inside of the `from_scalars` method.
Additionally improves the documentation to note the various failure cases, i.e. if `r` and/or `s` is out of the range `1..n`, where `n` is the scalar modulus.

ecdsa: refactor `Signature` constructors and improve docs

---

ecdsa/src/hazmat.rs

Extracts generic, reusable functions from the `SignPrimitive` and `VerifyPrimitive` traits.
The main motivation for this is to make it possible for the `*Primitive` trait impls to be composed in terms of a generic implementation, in order to add support for low-S normalization in the `k256` crate.

ecdsa: extract `hazmat::{sign_prehashed, verify_prehashed}`.

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- `hazmat::{sign_prehashed, verify_prehashed}` ([#731])
- Refactor `Signature` constructors and improve docs ([#730])
[#730]: https://github.com/RustCrypto/signatures/pull/730
[#731]: https://github.com/RustCrypto/signatures/pull/731

ecdsa v0.16.8

---

Cargo.lock
ed25519/Cargo.toml
ed25519/src/lib.rs

This is used as a `dev-dependency` for doctesting rustdoc documentation showing how to use the trait-based API.

ed25519: bump `ed25519-dalek` to v2

---

Cargo.lock
ed25519/CHANGELOG.md
ed25519/Cargo.toml

- Bump `ed25519-dalek` to v2 ([#738])
[#738]: https://github.com/RustCrypto/signatures/pull/738

ed25519 v2.2.2

---

ed25519/Cargo.toml

When we enable the `std` feature and the `pkcs8` dependency is enabled (by the `pem` feature), enable the `std` feature of `pkcs8`.
This makes it easier to work with the re-exported `pkcs8::Error` type because without the `std` feature it does not impl the  `std::error::Error` marker trait.

ed25519: enable `pkcs8/std` feature when `std` is enabled

---

ecdsa/src/lib.rs
ecdsa/src/normalized.rs
ed25519/src/hex.rs
ed25519/src/lib.rs
ed25519/tests/serde.rs

Formats the `R` and `s` signature components as hexidecimal to make the representation more compact, as requested in #723:
```rust
ed25519::Signature {
R: 0x3f3e3d3c3b3a393837363534333231302f2e2d2c2b2a29282726252423222120,
s: 0x1f1e1d1c1b1a191817161514131211100f0e0d0c0b0a09080706050403020100,
}
```

ed25519: hexify `Debug` impl on `Signature`

---

Cargo.lock
ed25519/CHANGELOG.md
ed25519/Cargo.toml

- Bump `ring-compat` from 0.7 to 0.8 ([#744])
- Enable `pkcs8/std` feature when `std` feature is enabled ([#746])
- Hex-format `Signature` components in `Debug` impl ([#747])
[#744]: https://github.com/RustCrypto/signatures/pull/744
[#746]: https://github.com/RustCrypto/signatures/pull/746
[#747]: https://github.com/RustCrypto/signatures/pull/747

ed25519 v2.2.3

---

ed25519/tests/pkcs8.rs
ed448/Cargo.toml
ed448/README.md
ed448/src/lib.rs
ed448/tests/pkcs8.rs

Hi there.
I added ed448 documentation.
There are a lot of duplication in between ed25519 and ed448 implementation.
As I mentioned in https://github.com/RustCrypto/signatures/pull/727, we can implement `eddsa` by combining them.
Is it too early to work on it?
I would appreciate it if you could confirm.
Thank you.

ed448: add documentation

---

dsa/Cargo.toml
ecdsa/Cargo.toml

The v2.2.0 release bumped MSRV to 1.60, however that's still compatible with the MSRV of `dsa` and `ecdsa`, which are both MSRV 1.65.

dsa+ecdsa: support `signature` up to v2.2

---

Cargo.lock
dsa/CHANGELOG.md
dsa/Cargo.toml

- Loosen `signature` bound to `2.0, <2.3` ([#756])
[#756]: https://github.com/RustCrypto/signatures/pull/756

dsa v0.6.2

---

Cargo.lock
ecdsa/CHANGELOG.md
ecdsa/Cargo.toml

- Loosen `signature` bound to `2.0, <2.3` ([#756])
[#756]: https://github.com/RustCrypto/signatures/pull/756

ecdsa v0.16.9

---

.github/workflows/dsa.yml
.github/workflows/ecdsa.yml
.github/workflows/ed25519.yml
.github/workflows/ed448.yml
.github/workflows/rfc6979.yml
.github/workflows/workspace.yml
Cargo.lock
dsa/Cargo.toml
dsa/README.md
ecdsa/Cargo.toml
ecdsa/README.md
ecdsa/src/der.rs
ecdsa/src/dev.rs
ecdsa/src/hazmat.rs
ecdsa/src/lib.rs
ecdsa/src/recovery.rs
ecdsa/src/signing.rs
ecdsa/src/verifying.rs
ed25519/Cargo.toml
ed25519/README.md
ed25519/src/lib.rs
ed448/Cargo.toml
ed448/README.md
rfc6979/Cargo.toml
rfc6979/README.md
rfc6979/src/ct_cmp.rs
rfc6979/src/lib.rs

For `ecdsa` crate: MSRV is 1.73 due to a bump of `elliptic-curve` to v0.14.0-pre.0.
This commit begins the next round of breaking changes and bumps all crates to prerelease versions.
The main change in `signature` is an upgrade of the `digest` crate to v0.11.0-pre.3, which is what brings the new MSRV 1.71 requirement.

Bump `signature` to v2.3.0-pre.0; MSRV 1.71

---

ecdsa/src/dev.rs

The method changed from `GenericArray::from_slice` to `Array::ref_from_slice`.
This has been renamed back upstream in `hybrid-array` to simplify people's upgrades, but for now we need to rename it until we can upgrade `hybrid-array` again.
Longer term the method will be deprecated, so this is temporary anyway.

ecdsa: fix `dev` macros

---

Cargo.lock
dsa/Cargo.toml
ecdsa/Cargo.toml
ecdsa/src/dev.rs
ed25519/Cargo.toml
ed448/Cargo.toml
rfc6979/Cargo.toml

As well as bumping `hybrid-array` to v0.2.0-rc.0 and `digest` to v0.11.0-pre.4.
Also cuts `ecdsa` v0.17.0-pre.1 and `rfc6979` v0.5.0-pre.1

Bump `elliptic-curve` and `signature` dependencies

---

ecdsa/src/dev.rs

Updates `from_exact_iter` => `from_iter`

ecdsa: fix `new_wycheproof_test!` macro

---

Cargo.lock
ecdsa/Cargo.toml

Also cuts a v0.17.0-pre.2 release of `ecdsa`.

ecdsa: bump `elliptic-curve` to v0.14.0-pre.2

---

ecdsa/src/der.rs

There's no Appendix A in RFC 5912. I think, it's a leftover from the previous reference to RFC 5480.

Fixed rfc reference in comment

---

Cargo.lock
ecdsa/src/hazmat.rs
rfc6979/src/ct_cmp.rs
rfc6979/src/lib.rs

Adds an API which writes `k` into an output buffer rather than allocating and returning it, which also accepts slices as inputs. This makes it possible to use `rfc6979` to implement the `dsa` crate.
Also removes output size bounds on the underlying digest function, which aren't actually relevant to the implementation at all since HMAC-DRBG writes a variable-sized amount of output. This makes it possible to use `rfc6979` + `ecdsa` in conjunction with `p521`, which has unusually sized scalars (66-bytes) which don't match the output size of the underlying digest function (SHA-512, which has a 64-byte output).

rfc6979: add `generate_k_mut`; remove digest bounds

---

ecdsa/src/hazmat.rs
ecdsa/src/signing.rs
ecdsa/src/verifying.rs

Notably for curves like P-521, the digest used to compute the signature is smaller than a serialized field element (SHA-512 w\ 64-byte output vs 66-byte serialized field elements).
To support such curves, we need to remove this bound.
The already implemented `bits2field` function as defined in RFC6979 § 2.3.2 and SEC1 § 2.3.8 handles producing a serialized field element from an input which may be a different size.

ecdsa: remove `OutputSize` bounds on `DigestPrimitive`

---

ecdsa/src/hazmat.rs

The RFC specifies this, however we were not performing it.
Going forward, it would be nice to be able to refactor these APIs to operate over a `Scalar` which we know is always reduced.

ecdsa: reduce `z` mod `q` when performing RFC6979

---

ecdsa/src/lib.rs

Unconditionally returns a normalized signature, regardless of whether the signature was normalized to begin with.
Closes #736

ecdsa: make `Signature::normalize_s` infallible

---

ecdsa/src/signing.rs
ecdsa/src/verifying.rs

...rather than `pem`, as these can be used to encode DER without having full `pem` support enabled.
Closes #721

ecdsa: gate `pkcs8::Encode*Key` impls under `alloc`+`pkcs8`

---

.github/workflows/dsa.yml
.github/workflows/ed25519.yml
.github/workflows/ed448.yml
.github/workflows/rfc6979.yml
.github/workflows/workspace.yml
Cargo.lock
dsa/Cargo.toml
dsa/README.md
ecdsa/Cargo.toml
ecdsa/src/lib.rs
ed25519/Cargo.toml
ed25519/README.md
ed448/Cargo.toml
ed448/README.md
rfc6979/Cargo.toml
rfc6979/README.md

Bumps the following dependencies:
- `digest` v0.11.0-pre.7
- `elliptic-curve` v0.14.0-pre.3
- `signature` v2.3.0-pre.2

Bump `digest`, `elliptic-curve`, and `signature`

---

ecdsa/src/lib.rs

Adds the following methods:
- `from_der_with_digest`
- `from_der_with_oid`
- `to_der`
These handle deserializing/serializing ASN.1 DER-encoded signatures.

ecdsa: add DER support to `SignatureWithOid`

---

ecdsa/src/hazmat.rs

This trait is the intended successor to the `SignPrimitive` and `VerifyPrimitive` traits.
Currently the only reason for a non-default impl of those traits is to handle low-S normalization. The `EcdsaCurve` trait now not only marks the curve as being safe for use with ECDSA, but also captures this decision regarding low-S normalization so it doesn't have to be expressed in code.

ecdsa: add `EcdsaCurve` marker trait

---

ecdsa/src/hazmat.rs

There's no reason for it to be gated on `arithmetic`. It can be provided in all use cases.

ecdsa: don't feature-gate `EcdsaCurve`

---

ecdsa/src/hazmat.rs
ecdsa/src/lib.rs

Moves the trait added in #787 out of the `hazmat` module and into the toplevel, so it's available regardless of whether or not the `hazmat` feature has been enabled.

ecdsa: move `EcdsaCurve` trait to toplevel

---

ecdsa/src/dev.rs
ecdsa/src/hazmat.rs
ecdsa/src/recovery.rs
ecdsa/src/signing.rs
ecdsa/src/verifying.rs

The backstory of these traits was once upon a time we didn't yet have the trait structure in place to express algorithms like ECDSA signing and verification generically, so each crate (at the time just `k256` and `p256`) had a nearly duplicated implementation of ECDSA, with `k256` including tweaks for low-S normalization.
Now the `ecdsa` crate contains fully generic implementations of both algorithms, and with the `EcdsaCurve` trait, carries a `NORMALIZE_S` preference, so these traits are just needless indirection at this point.
This removes the traits, converting non-trivial methods into static functions in the `hazmat` module, namely `sign_prehashed_rfc6979`.

ecdsa: remove `SignPrimitive` and `VerifyPrimitive` traits

---

ecdsa/src/dev.rs
ecdsa/src/hazmat.rs
ecdsa/src/signing.rs

Provides type-level enforcement that these parameters are non-zero

ecdsa: use `NonZeroScalar` arguments to `sign_prehashed`

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/hazmat.rs
ecdsa/src/recovery.rs

Notably this includes the newly refactored `LinearCombination` trait

ecdsa: bump `elliptic-curve` to v0.14.0-pre.5

---

Cargo.lock
Cargo.toml
dsa/src/components.rs
dsa/src/lib.rs
ecdsa/src/der.rs

See https://github.com/RustCrypto/formats/pull/1055 for more info.

Add support for custom error types in `der`.

---

.github/workflows/slh-dsa.yml
slh-dsa/src/fors.rs
slh-dsa/src/hypertree.rs
slh-dsa/src/signature_encoding.rs
slh-dsa/tests/known_answer_tests.rs

* Fully guard alloc tests with feature flags, make KATs no-alloc
* Move imports used only in alloc tests into the test functions to avoid clippy lints
* Enable CI tests with `--no-default-features`

SLH-DSA: Fix tests with `--no-default-features` and enable CI

---

Cargo.lock
lms/CHANGELOG.md
lms/Cargo.toml
lms/README.md

lms-signature v0.0.1

---

ecdsa/src/der.rs
ecdsa/src/verifying.rs

rust 1.78 introduced new unnecessary qualification warnings.

ecdsa: fixup `unnecessary qualification` warnings

---

slh-dsa/Cargo.toml
slh-dsa/LICENSE-APACHE
slh-dsa/LICENSE-MIT
slh-dsa/README.md

Standard license used by other RustCrypto projects.
cc @tjade273 for approval.

slh-dsa: adopt Apache 2.0 + MIT licensing

---

ecdsa/src/verifying.rs

>I am using verify_prehash() with P521 curve to verify a der::Signature and find that I cannot compile the codes because that DigestPrimitive is not implemented for NistP521.
>
>I think there is no need to add this trait bound after I invested the codes. I wonder If this is something forget to be removed.
> 
> -- From [Zulip topic](https://rustcrypto.zulipchat.com/#narrow/stream/260048-signatures/topic/Do.20.60PrehashVerifier.60.20really.20need.20.60C.3A.20DigestPrimitive.60.3F)

Remove unnecessary DigestPrimitive bound on PrehashVerifier

---

Cargo.lock
ecdsa/src/recovery.rs

If the recovered public key isn't correct, an error occurs when comparing it to the correct public key or public key hash. Therefore, we can skip this expensive verification.
See discussion in https://github.com/RustCrypto/signatures/issues/751

ecdsa: add recover_from_prehash_noverify

---

ecdsa/src/recovery.rs

Since the recovered public key is eventually authenticated through comparison, verifying the public key on each attempt is unnecessary.

ecdsa: optimize `trial_recovery_from_prehash` using `recover_from_prehash_noverify`

---

ed448/src/pkcs8.rs

The crate doesn't currently have a `zeroize` feature but has code gated under it.
This removes the code in question to fix the build until such a time as a proper `zeroize` feature can be added.

ed448: fix build

---

Cargo.lock
ecdsa/src/lib.rs
slh-dsa/src/fors.rs
slh-dsa/src/hashes/sha2.rs
slh-dsa/src/signature_encoding.rs
slh-dsa/src/signing_key.rs
slh-dsa/src/util.rs
slh-dsa/src/verifying_key.rs

Bump `hybrid-array` to v0.2.0-pre.9

---

Cargo.lock
Cargo.toml
dsa/Cargo.toml
ecdsa/Cargo.toml
ed25519/Cargo.toml
ed448/Cargo.toml
lms/Cargo.toml
ml-dsa/Cargo.toml
rfc6979/Cargo.toml
slh-dsa/Cargo.toml

Bumps the following dependencies:
- `der` v0.8.0-rc.0
- `digest` v0.11.0-pre.9
- `elliptic-curve` v0.14.0-pre.6
- `pkcs8` v0.11.0-rc.0
- `sha2` v0.11.0-pre.4
- `signature` v2.3.0-pre.4
- `spki` v0.8.0-rc.0

Use new prerelease/release candidate dependencies

---

slh-dsa/Cargo.toml

This patch fixes slh-dsa build for non-std targets.
Without this patch, `cargo build --target thumbv7m-none-eabi --no-default-features` fails due to std usage in `crypto-common`.

slh-dsa: fix no_std

---

Cargo.lock
slh-dsa/Cargo.toml
slh-dsa/src/address.rs

...rather than directly depending on `zerocopy-derive`.
This fixes problems that arise if the `derive` feature is enabled by other dependencies in the same tree. See #846.

slh-dsa: enable `derive` feature of `zerocopy`

---

ecdsa/Cargo.toml

Removes the leading `=` requirement from these dependencies, since they're both `rc.0`

ecdsa: unpin `der` and `spki` dependencies

---

Cargo.lock
slh-dsa/CHANGELOG.md
slh-dsa/Cargo.toml

- Implement changes from FIP 205 Initial Public Draft -> FIPS 205 Final ([#844])
- `no_std` support ([#845])
- Enable `derive` feature of `zerocopy` ([#847])
[#844]: https://github.com/RustCrypto/signatures/pull/844
[#845]: https://github.com/RustCrypto/signatures/pull/845
[#847]: https://github.com/RustCrypto/signatures/pull/847

slh-dsa v0.1.0

---

Cargo.lock
Cargo.toml
dsa/src/signing_key.rs
ecdsa/Cargo.toml
ecdsa/src/der.rs
ecdsa/src/signing.rs
ed25519/src/pkcs8.rs
ed448/src/pkcs8.rs

related to https://github.com/RustCrypto/formats/pull/1483
Depends: 
- https://github.com/RustCrypto/traits/pull/1650

ecdsa,dsa,ed25519,ed448: pkcs8 API changes

---

Cargo.lock
Cargo.toml

Now https://github.com/RustCrypto/traits/pull/1650 merged the branch has been removed.

workspace: move back to traits.git/master

---

Cargo.lock
Cargo.toml
dsa/Cargo.toml
ecdsa/Cargo.toml
ed25519/Cargo.toml
ed448/Cargo.toml

This bump the following dependencies:
- pkcs8 0.11.0-rc.0 -> 0.11.0-rc.1
- elliptic-curve 0.14.0-pre.6 -> 0.14.0-rc.0
This is a followup on breaking changes made on pkcs8 (https://github.com/RustCrypto/formats/pull/1483).

bump pkcs8 dependency after breaking change

---

Cargo.lock
slh-dsa/Cargo.toml
slh-dsa/src/hashes/sha2.rs

slh-dsa: use pre-release versions

---

Cargo.toml
dsa/Cargo.toml
ecdsa/Cargo.toml

This makes use of a global `patch.crates-io` instead of local `path =` attributes in the dependencies.
When pulling dependencies through git to try unreleased crates, the dependency in `path` will get duplicated. Which makes for twice the definition of types incompatible with each other.

workspace: limit duplicate dependencies

---

ecdsa/Cargo.toml
ecdsa/src/verifying.rs

To get `serde` support for `VerifyingKey`, confusingly the `pem` feature previously needed to be enabled (even though PEM is not actually used).
This changed the `serde` feature to auto-enable `pkcs8`, similar to what was done in the `elliptic-curve` crate.

ecdsa: simplify `serde` feature

---

slh-dsa/src/hashes.rs
slh-dsa/src/hashes/sha2.rs
slh-dsa/src/hashes/shake.rs
slh-dsa/src/signing_key.rs
slh-dsa/src/verifying_key.rs
slh-dsa/tests/acvp_sig.rs
slh-dsa/tests/acvp_ver.rs
slh-dsa/tests/known_answer_tests.rs

This PR takes care of some TODO's in the sign and verify functions in the slh-dsa crate, thereby resolving #854
I'm passing the new messages parts on the stack as slice references down into the functions h_msg and prf_msg so that each part can be .update()'ed into the digest without having to copy them into new memory. I think it could be improved with some type system wizardry to enforce the layout specified in FIPS 205, but that's a bit beyond my abilities.

Remove allocation in slh-dsa

---

lms/src/lms/private.rs

`otstype` is converted as a `u32` below, panics if it is `ID_LEN` (16) bytes long. With this change, the `SigningKey` can be correctly converted to bytes and back.

lms: fix size of `otstype`

---

slh-dsa/src/util.rs

The build is failing because of a lint failure due to an undocumented macro which is only used for tests.
This adds a simple comment so the lint succeeds.

slh-dsa: fix lint

---

Cargo.lock
slh-dsa/Cargo.toml
slh-dsa/src/hashes/sha2.rs
slh-dsa/src/hashes/shake.rs
slh-dsa/src/lib.rs
slh-dsa/src/signature_encoding.rs
slh-dsa/src/signing_key.rs
slh-dsa/src/verifying_key.rs
slh-dsa/tests/pkcs8.rs

Made a demo w/ x509 over in https://github.com/baloo/playground-x509-slh-dsa
I guess this effectively implements a [draft RFC](https://datatracker.ietf.org/doc/draft-ietf-lamps-cms-sphincs-plus/)

slh-dsa: adds pkcs8 support

---

dsa/Cargo.toml
dsa/examples/export.rs
dsa/examples/generate.rs
dsa/examples/sign.rs
dsa/src/generate.rs
dsa/src/generate/keypair.rs
dsa/src/generate/secret_number.rs
dsa/src/lib.rs
dsa/src/signing_key.rs
dsa/tests/deterministic.rs
dsa/tests/signature.rs
dsa/tests/signing_key.rs
dsa/tests/verifying_key.rs

Adding signing under hazmat.

---

ecdsa/src/recovery.rs

This implements `RandomizedPrehashSigner<(Signature<C>, RecoveryId)>` and `RandomizedDigestSigner<(Signature<C>, RecoveryId)>` for `SigningKey<C>`. These do essentially the same thing as the `Signer<Signature<C>>` implementations, but they return rather than discard the `RecoveryId`.

feat: impl recoverable RandomizedPrehashSigner for SigningKey

---

ed25519/src/lib.rs

Fixes #888
cc @stevefan1999-personal @juliusl

ed25519: implement `SignatureBitStringEncoding` support

---

ml-dsa/Cargo.toml

It doesn't appear this feature actually does anything except transitively activate the `sha3/std` feature, which we likely plan on removing in the next breaking release.
Now that `core::error::Error` is stable, we are generally trying to remove `std` features across the @RustCrypto project, except in cases where libraries do things like e.g. file I/O (for loading/saving keys) and actually have a legitimate `std` dependency that way.

ml-dsa: remove `std` feature

---

ml-dsa/src/lib.rs
ml-dsa/tests/key-gen.rs
ml-dsa/tests/pkcs8.rs

Follow up on #891
This reworks the `ml_dsa::KeyPair` to keep the seed along with the `SigningKey` which allows to serialize the private key to the pkcs8 format after that.

ml-dsa: encode private key

---

ml-dsa/src/algebra.rs
ml-dsa/src/hint.rs
ml-dsa/src/lib.rs

Fixes #894 
This PR also adds a test that runs many random signatures.  I confirmed locally that this produced a failure rate of 0.4-1.1% for ML-DSA-65 and ML-DSA-87, all due to signature decoding, and all for the reasons discussed below.  I never saw any failures for ML-DSA-44, but that seems plausible: The failure condition arises when the high-order bits of the `r` vector don't change, and the threshold $\gamma_2 / 2$ is roughly a factor of 2.75 lower for ML-DSA-44 than the other variants.
It appears that the root of the problem is a one-character fix, allowing repeated values in the monotonicity check in `hint.rs`.  This makes it so that the tests usually pass.  Marking this PR as draft because that same test fails intermittently, reporting `internal error: entered unreachable code` …

Make ML-DSA signature decoding follow the spec

---

ml-dsa/Cargo.lock
ml-dsa/Cargo.toml
ml-dsa/LICENSE-MIT

ml-dsa v0.1.0-pre.2

---

ml-dsa/Cargo.lock
ml-dsa/Cargo.toml

Tiny change, but... my first for RustCrypto stuffs, so I'm super excited.
As far as I can tell, this is the only change need to make ml-dsa build against signatures@2.3.6-pre.6.
Have an awesome day and happy Rust 1.85! 💖 🦀

ml-dsa: update signature@2.3.0-pre.6

---

ml-dsa/Cargo.lock
ml-dsa/Cargo.toml

As far as I can tell, this is the only change need to make ml-dsa build against pkcs8 0.11.0-rc.2.

ml-dsa: update pkcs8@0.11.0-rc.2

---

.github/workflows/ml-dsa.yml

This is something to consider after #921 lands. It makes sure the benchmarks can build against the current code.

ml-dsa: cargo build --benches in github workflow

---

.cargo/audit.toml
.github/workflows/security-audit.yml

Ignores RUSTSEC-2024-0436: `paste` is unmaintained

CI: fix security audit

---

Cargo.lock
Cargo.toml
ecdsa/src/signing.rs

Depends:
- https://github.com/zkcrypto/ff/pull/126
- https://github.com/zkcrypto/ff/pull/127
- https://github.com/RustCrypto/traits/pull/1774

ecdsa: provide a SigningKey::try_from_rng

---

ecdsa/Cargo.toml

We have a `digest` feature already, which can be used to enable this as needed

ecdsa: remove default `elliptic-curve/digest` feature

---

.github/workflows/slh-dsa.yml
slh-dsa/benches/sign_verify.rs

The sign_verify.rs benchmark was running the signing benchmarks twice. This fixes that so the verification benchmarks are also run.

slh-dsa: fix benchmark to also run verify_benches()

---

Cargo.lock
slh-dsa/CHANGELOG.md
slh-dsa/Cargo.toml

Backport release with a looser `signature` v2 dependency

slh-dsa v0.0.3

---

Cargo.lock
Cargo.toml
ml-dsa/Cargo.toml
ml-dsa/benches/ml_dsa.rs
ml-dsa/src/encode.rs
ml-dsa/src/lib.rs
slh-dsa/Cargo.toml
slh-dsa/benches/sign_verify.rs
slh-dsa/src/fors.rs
slh-dsa/src/hashes/sha2.rs
slh-dsa/src/hashes/shake.rs
slh-dsa/src/hypertree.rs
slh-dsa/src/lib.rs
slh-dsa/src/signature_encoding.rs
slh-dsa/src/signing_key.rs
slh-dsa/src/verifying_key.rs
slh-dsa/src/wots.rs
slh-dsa/src/xmss.rs
slh-dsa/tests/known_answer_tests.rs

This reverts commit 64b55c6393736de5a89b9b4c64f013d680945eef from #931
This was done to kick out some releases, which have now been published, so these crates are going back to using the latest development releases.

Revert "downgrade ml-dsa and slh-dsa to non-prerelease deps"

---

.github/workflows/ml-dsa.yml
ml-dsa/Cargo.toml
ml-dsa/src/lib.rs

The CI workflow should build/test with --no-default-features to catch any issues with that configuration.
There is currently 1 warning when building ml-dsa with --no-default-features, and 1 failing doc-test. I'll fix those in upcoming commits, but I first want to run this though the CI to make sure it fails as expected.

ml-dsa: cargo test with --no-default-features in workflow

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/lib.rs

This PR implements `Zeroize` for `ecdsa::Signature` by setting both scalars to one, which is still a valid signature and upholds the types invariants.

Implement `Zeroize` for `ecdsa::Signature`

---

dsa/src/signing_key.rs

Resolves #883 by implementing `ZeroizeOnDrop` for `dsa::SigningKey`.
Since the private component `x` already is of type `Zeroizing<BigUint>`, no changes were necessary to ensure the `ZeroizeOnDrop` preconditions were met.

dsa: impl ZeroizeOnDrop for SigningKey

---

slh-dsa/src/fors.rs
slh-dsa/src/hypertree.rs
slh-dsa/src/lib.rs
slh-dsa/src/signature_encoding.rs
slh-dsa/src/signing_key.rs
slh-dsa/src/verifying_key.rs
slh-dsa/src/wots.rs
slh-dsa/src/xmss.rs

correct following configuration from:
```rs
#![cfg_attr(not(feature = "alloc"), no_std)]
```
to
```rs
#![no_std]
```

refactor: improve no_std support for slh-dsa

---

ecdsa/src/signing.rs

I *think* this was missed in in #955 as this came in #947 which I did not revert.

ecdsa: restore `RandomizedSigner<der::Signature>`

---

Cargo.lock
Cargo.toml
dsa/Cargo.toml
dsa/src/generate/secret_number.rs
dsa/src/verifying_key.rs

See:
- https://github.com/RustCrypto/crypto-bigint/pull/817
Depends:
- https://github.com/RustCrypto/traits/pull/1845

chore(deps): bump `crypto-bigint` to `0.7.0-pre.3`, use core naming conventions

---

slh-dsa/src/hashes/sha2.rs
slh-dsa/src/hashes/shake.rs
slh-dsa/src/util.rs

`cargo clippy --all --all-features --fix`
could not fix these.
`usize` added manually.
Looks like a bug in
- https://github.com/rust-lang/rust-clippy/pull/12987

apply nightly clippy fixes: const `div_ceil` (2025-05-12)

---

Cargo.lock
Cargo.toml
dsa/Cargo.toml
ecdsa/Cargo.toml
ed25519/Cargo.toml
ed448/Cargo.toml
lms/Cargo.toml
ml-dsa/Cargo.toml
rfc6979/Cargo.toml
slh-dsa/Cargo.toml

Also bumps:
- `elliptic-curve` v0.14.0-rc.2
- `signature` v3.0.0-rc.0

Bump `digest` dependency to v0.11.0-rc.0

---

dsa/Cargo.toml
dsa/src/signing_key.rs

- Place attributes after comments
- Ensure `hazmat` features are documented on docs.rs

dsa: minor `hazmat` cleanups

---

dsa/Cargo.toml
dsa/src/lib.rs

It isn't actually used for anything, and with a hard dependency on `alloc` and `core::error::Error` we can always capture `Box<std::error::Error>` in `signature::Error`.

dsa: remove `std` feature

---

ed25519/src/lib.rs
ed448/src/lib.rs

See <https://datatracker.ietf.org/doc/html/rfc8410#section-3>

ed448: implement `AssociatedAlgorithmIdentifier` for `Signature`

---

Cargo.lock

Cargo.lock: bump `bumpalo` to v3.18.1

---

ecdsa/src/der.rs

This way we avoid using internals of `der`:
- `der::SliceWriter`
- `der::SliceReader`
- `tag.assert_eq`
- `writer.sequence`

ecdsa: der: use impl `EncodeValue`/`DecodeValue` on `SignatureRef`

---

dsa/tests/signature.rs
ecdsa/src/der.rs
ecdsa/src/hazmat.rs
ecdsa/src/recovery.rs
ed25519/src/pkcs8.rs
ed25519/src/serde.rs
ed448/src/pkcs8.rs
ed448/src/serde.rs
ml-dsa/src/algebra.rs
ml-dsa/src/lib.rs

`rustc 1.85.0`
`cargo clippy --all --all-features --tests`

all: test: apply cargo clippy fixes

---

Cargo.lock
ecdsa/Cargo.toml
ecdsa/src/der.rs

This version notably automatically handles setting up a nested `Reader` for passing to `DecodeValue::decode_value`, eliminating the need to do it manually.
Also cuts an `ecdsa` v0.17.0-rc.3

ecdsa: bump `der` to v0.8.0-rc.5

---

Cargo.lock
dsa/Cargo.toml

Includes `crypto-bigint` v0.7.0-pre.5 upgrade

dsa v0.7.0-rc.1

---

Cargo.lock
Cargo.toml
dsa/Cargo.toml
ecdsa/Cargo.toml

Bumps the following:
- crypto-bigint v0.7.0-pre.6
- der v0.8.0-rc.6
- elliptic-curve v0.14.0-rc.8
- pkcs8 v0.11.0-rc.5
- sec1 v0.8.0-rc.6
- spki v0.8.0-rc.3

dsa+ecdsa: bump dependencies

---

ml-dsa/src/lib.rs

Introduce a utility method to derive a `VerifyingKey` from a `SigningKey`, even when the original seed or precomputed public key is unavailable. This aids in scenarios where private keys are imported from external sources lacking associated public key data.

feat(ml-dsa): Implement verifying_key method for SigningKey

---

Cargo.lock
dsa/Cargo.toml
ecdsa/Cargo.toml
rfc6979/Cargo.toml

Releases the following:
- `dsa` v0.7.0-rc.5
- `ecdsa` v0.17.0-rc.6
- `rfc6979` v0.5.0-rc.1

Cut prereleases with `hybrid-array` v0.4 support

---

Cargo.lock
Cargo.toml
dsa/Cargo.toml
ecdsa/src/lib.rs

ecdsa: renames `ScalarPrimitive` to `ScalarValue`
Companion PR to RustCrypto/traits#2008

Bump `crypto-bigint` to v0.7.0-rc.5

---

Cargo.lock
dsa/Cargo.toml
lms/Cargo.toml
ml-dsa/Cargo.toml
slh-dsa/Cargo.toml
slh-dsa/benches/sign_verify.rs

Bumps the following:
- `aes` v0.9.0-rc.1
- `cipher` v0.5.0-rc.1
- `criterion` v0.7
- `ctr` v0.10.0-rc.1
- `hex-literal` v1
- `sha3` v0.11.0-rc.3

Bump dependencies in Cargo.toml(s)

---

Cargo.lock
slh-dsa/Cargo.toml
slh-dsa/src/address.rs

The `AsBytes` trait is gone, and now found on the `IntoBytes` trait.
It needs a new `Immutable` marker trait which says:
> Types which are free from interior mutability.
...so it seems safe to add to the types that previously used `AsBytes` which are simple data structs.

slh-dsa: bump `zerocopy` to v0.8

---

ml-dsa/Cargo.toml

The `sha3` crate by default [enables `alloc` and `oid`](https://docs.rs/crate/sha3/0.11.0-rc.3/features), which aren't needed. I checked it locally with `cargo check -p ml-dsa --all-features`. I assume this was just an oversight, since `slh-dsa` already disables the default features for `sha3`:
https://github.com/RustCrypto/signatures/blob/8aa41de7b88f1e25711f54151367b954ab08e814/slh-dsa/Cargo.toml#L21

Disable default features for `sha3`
