RustCrypto/signatures

signature-crate/Cargo.toml, signature-crate/src/lib.rs, signature-crate/src/signature.rs
Also a few comment/import cleanups in `lib.rs`
=> Cargo.toml: Add more information and improve formatting

signature-crate/src/signer.rs
For many signature providers (i.e. most software implementations), it's not possible for an error to occur when creating a signature. Support for handling errors which occur when computing signatures is intended for use with cloud KMS, HSMs, or other hardware tokens where things like I/O errors are possible.
To simplify usage in the event that only software signers are in use, this commit splits the `sign` API into `Result`-based `try_sign` method and another `sign` method that always assumes success and unwraps the result of the former method.
=> Add `try_*` methods to `*Signer` traits

ed25519/CHANGES.md, ed25519/Cargo.toml
=> ed25519 v0.1.0

ecdsa/Cargo.toml, ed25519/Cargo.toml, signature-crate/CHANGES.md, signature-crate/Cargo.toml, signature-crate/signature_derive/Cargo.toml, signature-crate/src/lib.rs
- Revert removal of `DigestSignature` ([#33])
- 1.0 stabilization proposal ([#32])
[#33]: https://github.com/RustCrypto/signatures/pull/33
[#32]: https://github.com/RustCrypto/signatures/pull/32
=> signature 1.0.0-pre.0

ecdsa/Cargo.toml, ecdsa/README.md, ecdsa/src/asn1_signature.rs, ecdsa/src/curve.rs, ecdsa/src/curve/nistp256.rs, ecdsa/src/curve/nistp384.rs, ecdsa/src/curve/point.rs, ecdsa/src/curve/secp256k1.rs, ecdsa/src/lib.rs
Adds a README.md and improves comments throught the codebase.
=> ecdsa: Improve documentation

ecdsa/CHANGES.md, ecdsa/Cargo.toml, ecdsa/src/lib.rs
=> ecdsa v0.1.0

ed25519/src/lib.rs
Ensures that the three highest bits of the `s` scalar component of an Ed25519 signature are unset.
This doesn't ensure that `s` is fully reduced (which would require a full reduction check in the event that the 4th most significant bit is set), however it will catch a number of invalid signatures relatively
cheaply.
Inspired by:
https://github.com/dalek-cryptography/ed25519-dalek/pull/99
=> ed25519: Perform partial reduction check on `Signature`

ecdsa/Cargo.toml, elliptic-curve-crate/CHANGES.md, elliptic-curve-crate/Cargo.toml, elliptic-curve-crate/README.md, elliptic-curve-crate/src/lib.rs
=> elliptic-curve v0.1.0

ecdsa/CHANGES.md, ecdsa/Cargo.toml, ecdsa/src/lib.rs
- Use curve types from the `elliptic-curve` crate (#58)
=> ecdsa v0.2.0

README.md, ecdsa/Cargo.toml, ed25519/Cargo.toml
See: https://github.com/RustCrypto/traits/blob/master/signature/CHANGES.md#100-pre3-2020-03-08
=> Upgrade to `signature` crate v1.0.0-pre.3

build_nostd.sh, ecdsa/Cargo.toml, ecdsa/src/asn1_signature.rs, ecdsa/src/convert.rs, ecdsa/src/fixed_signature.rs, ed25519/Cargo.toml, ed25519/src/lib.rs, signature-crate/README.md
Changelog here: https://github.com/RustCrypto/traits/pull/90
=> Update signature requirement to v1.0.0-pre.5

Cargo.lock, ecdsa/Cargo.toml, ecdsa/src/curve/nistp256.rs, ecdsa/src/curve/nistp384.rs, ecdsa/src/curve/secp256k1.rs, ed25519/Cargo.toml
More info on this release: https://github.com/RustCrypto/traits/issues/78
=> Upgrade to v1.0 release of the `signature` crate

Cargo.lock, ed25519/CHANGES.md, ed25519/Cargo.toml, ed25519/src/lib.rs
- Usage documentation ([#83])
[#83]: https://github.com/RustCrypto/signatures/pull/83
=> ed25519 v1.0.1

ecdsa/src/hazmat.rs
Avoids re-declaring the associated type
=> ecdsa: bound ecdsa::SignPrimitive on Arithmetic

ecdsa/README.md, ecdsa/src/lib.rs
Notes the crate now contains a generic ECDSA implementation
=> ecdsa: update README.md and rustdoc intros

ecdsa/src/asn1.rs
Requires the `digest` and `hazmat` features
=> ecdsa: add conditional PrehashSignature impl for asn1::Signature

Cargo.lock, ecdsa/CHANGELOG.md, ecdsa/Cargo.toml, ecdsa/src/lib.rs
- Conditional `PrehashSignature` impl for `asn1::Signature` ([#128])
[#128]: https://github.com/RustCrypto/signatures/pull/128
=> ecdsa v0.7.2

.github/workflows/workspace.yml
- Upgrade `cargo-tarpaulin` to v0.14.3
- Upgrade `codecov-action` to v1.0.13
- Run cargo-tarpaulin with --all-features
=> .github: update tarpaulin + codecov config

Cargo.lock, ecdsa/src/dev/curve.rs
=> ecdsa: rename FieldBits => ScalarBits

Cargo.lock, ecdsa/src/dev/curve.rs, ecdsa/src/sign.rs
Corresponding change for RustCrypto/traits#295.
=> ecdsa: remove `Generate` trait

Cargo.lock, ecdsa/src/dev.rs, ecdsa/src/dev/curve.rs, ecdsa/src/lib.rs, ecdsa/src/rfc6979.rs, ecdsa/src/sign.rs
=> ecdsa: FromFieldBytes updates

Cargo.lock, ed25519/CHANGES.md, ed25519/Cargo.toml, ed25519/src/lib.rs
- `ed25519-dalek` usage example ([#167])
[#167]: https://github.com/RustCrypto/signatures/pull/167
=> ed25519 v1.0.2

ecdsa/src/verify.rs
...in cases where AffinePoint<C> is a `Copy` type
=> ecdsa: conditionally make VerifyKey<C> a Copy type

.github/workflows/ecdsa.yml, Cargo.lock, ecdsa/Cargo.toml, ecdsa/src/dev/curve.rs
They weren't tested before. They are now!
=> ecdsa: fix 32-bit builds for the `dev` feature

.github/workflows/ecdsa.yml, ecdsa/src/hazmat.rs
Also CIs for `arithmetic`+`hazmat` and `digest`+`hazmat` feature combos
=> ecdsa: fix digest+hazmat feature combo

Cargo.lock, ecdsa/Cargo.toml, ecdsa/src/lib.rs
Reflect that the code on master contains breaking changes
=> ecdsa: bump version to v0.12.0-pre

Cargo.lock, ecdsa/CHANGELOG.md, ecdsa/Cargo.toml, ecdsa/src/lib.rs
- Impl `Clone`, `Debug`, `*Eq` for `SigningKey` ([#345])
[#345]: https://github.com/RustCrypto/signatures/pull/345
=> ecdsa 0.12.4

ecdsa/src/hazmat.rs
Adds a helper trait for performing the 𝑘×𝑮 scalar multiplication used by ECDSA, with a subsequent reduction to a scalar field element.
The main purpose of having a special trait for this is so curve implementations can avoid exposing their base field implementations. This trait does just what's needed with base field elements for ECDSA.
With the addition of this trait, it's possible to have a generic implementation of ECDSA signatures which otherwise only relies on the existing curve arithmetic features.
=> ecdsa: add `MulBaseReduced` trait + generic ECDSA signing

ecdsa/src/dev.rs
Updates test macros with the changes from #396 and #397
=> ecdsa: fix test macros

Cargo.lock, ecdsa/Cargo.toml, rfc6979/CHANGELOG.md, rfc6979/Cargo.toml, rfc6979/src/lib.rs
=> rfc6979 v0.1.0

Cargo.lock, ecdsa/CHANGELOG.md, ecdsa/Cargo.toml, ecdsa/src/lib.rs
- `hazmat::rfc6979_generate_k` function ([#414])
[#414]: https://github.com/RustCrypto/signatures/pull/414
=> ecdsa v0.13.1

Cargo.lock, ecdsa/Cargo.toml, ecdsa/src/hazmat.rs, ecdsa/src/verify.rs
=> ecdsa: use revised `LinearCombination` trait

Cargo.lock, ed25519/CHANGELOG.md, ed25519/Cargo.toml, ed25519/README.md, ed25519/src/lib.rs
- License files ([#447])
- `pkcs8::PublicKeyBytes` type ([#455])
[#447]: https://github.com/RustCrypto/signatures/pull/447
[#455]: https://github.com/RustCrypto/signatures/pull/455
=> ed25519 v1.4.1

ecdsa/README.md, ed25519/README.md, rfc6979/README.md
Places the green badges next to each other
=> Update badge ordering in README.md files

Cargo.lock, dsa/CHANGELOG.md, dsa/Cargo.toml, dsa/README.md
=> dsa v0.2.0

ecdsa/src/der.rs, ecdsa/src/lib.rs
Uses the `serdect` crate (already a dependency) to serialize/deserialize `Signature` types.
Fixes RustCrypto/elliptic-curves#608.
=> ecdsa: use `serdect` for `Signature` types

ecdsa/src/recovery.rs
Adds a `const fn` by-value constructor
=> ecdsa: add `RecoveryId::from_byte`

ecdsa/src/der.rs, ecdsa/src/lib.rs
=> ecdsa: display hex in `Debug` impls for `Signature`

ecdsa/src/sign.rs
Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>
=> feat(ecdsa): impl From<SigningKey> for SecretKey

ed25519/src/pkcs8.rs
=> ed25519: remove addressed TODO

Cargo.lock, rfc6979/CHANGELOG.md, rfc6979/Cargo.toml
- Usage example ([#577])
[#577]: https://github.com/RustCrypto/signatures/pull/577
=> rfc6979 v0.3.1

ed25519/src/pkcs8.rs
These are needed to completely implement the `DecodePrivateKey`/`DecodePublicKey` and `EncodePrivateKey`/`EncodePublicKey` traits while relying only on `ed25519::pkcs8`.
=> ed25519: re-export `pkcs8` error types

ecdsa/src/der.rs, ecdsa/src/dev.rs, ecdsa/src/hazmat.rs, ecdsa/src/lib.rs, ecdsa/src/recovery.rs, ecdsa/src/signing.rs, ecdsa/src/verifying.rs, ed25519/src/lib.rs, ed25519/src/pkcs8.rs, ed25519/src/serde.rs, rfc6979/Cargo.toml, rfc6979/src/lib.rs
Generate feature-dependent rustdoc automatically rather than through manual annotations
=> Use `doc_auto_cfg`

.github/workflows/dsa.yml, .github/workflows/ecdsa.yml, .github/workflows/rfc6979.yml, Cargo.lock, Cargo.toml, dsa/Cargo.toml, dsa/README.md, ecdsa/Cargo.toml, ecdsa/README.md, ecdsa/src/der.rs, ecdsa/src/dev.rs, ecdsa/src/hazmat.rs, ecdsa/src/lib.rs, ecdsa/src/recovery.rs, ecdsa/src/signing.rs, ecdsa/src/verifying.rs, rfc6979/Cargo.toml, rfc6979/README.md
=> ecdsa: bump `elliptic-curve` to v0.13.0-pre; MSRV 1.61

ecdsa/src/hazmat.rs
Adds support for computing the recovery ID which can be used to recover the verifying key from the signature.
This makes use of the newly added `AffineYIsOdd` trait.
It also switches to using the `MulByGenerator` trait for basepoint multiplication.
=> ecdsa: compute `RecoveryId` from `SignPrimitive`

.github/workflows/security-audit.yml
Now that #640 is merged it should work again
=> CI: re-enable security audit

ecdsa/src/lib.rs
Adds inherent methods for parsing a signature from `SignatureBytes<C>` and a byte slice respectively.
The existing `TryFrom<&[u8]>` impl now calls `Signature::from_slice`.
These methods match similar inherent methods on other types.
=> ecdsa: add `Signature::{from_bytes, from_slice}`

ecdsa/src/dev.rs
Uses `C::FieldBytesSize` instead of `C::Uint::BYTES`, which is needed for curves like P-224 where the serialized field element may be smaller than the bigint used to represent them.
=> ecdsa: fix test macros handling of serialized field size

rfc6979/src/lib.rs
Restores a version of `generate_k` which operates over byte slices as opposed to fixed-size `Array`s.
Useful for implementing `dsa`.
=> rfc6979: restore `generate_k_mut`

dsa/src/signing_key.rs
Allows to use other digest algorithms.
=> feat(dsa): implement `SigningKey::sign_prehashed_rfc6979

ecdsa/src/recovery.rs
Replaces some manual branching and use of `unwrap()` with a more combinator-like style.
This could benefit from it being easier to convert `CtOption` into `Option`. See dalek-cryptography/subtle#119
=> ecdsa: refactor `VerifyingKey::recover_from_prehash`

Cargo.lock, slh-dsa/CHANGELOG.md, slh-dsa/Cargo.toml
=> slh-dsa v0.0.2

ml-dsa/Cargo.toml, ml-dsa/README.md
- Corrects dated references to the draft
- Also fixes the MSRV badge in README.md
=> ml-dsa: note crate implements FIPS 204 (final)

Cargo.lock, Cargo.toml, ml-dsa/Cargo.toml, ml-dsa/benches/ml_dsa.rs, ml-dsa/src/encode.rs, ml-dsa/src/lib.rs, slh-dsa/Cargo.toml, slh-dsa/benches/sign_verify.rs, slh-dsa/src/fors.rs, slh-dsa/src/hashes/sha2.rs, slh-dsa/src/hashes/shake.rs, slh-dsa/src/hypertree.rs, slh-dsa/src/lib.rs, slh-dsa/src/signature_encoding.rs, slh-dsa/src/signing_key.rs, slh-dsa/src/verifying_key.rs, slh-dsa/src/wots.rs, slh-dsa/src/xmss.rs, slh-dsa/tests/known_answer_tests.rs
Ref https://github.com/RustCrypto/signatures/issues/930
=> downgrade ml-dsa and slh-dsa to non-prerelease deps

Cargo.lock, ml-dsa/CHANGELOG.md, ml-dsa/Cargo.toml
=> ml-dsa v0.0.4

Cargo.lock, slh-dsa/Cargo.toml, slh-dsa/src/signing_key.rs
=> feat(slh-dsa): add zeroize support for SigningKey

Cargo.lock, Cargo.toml, ecdsa/src/hazmat.rs
follow-up to:
- https://github.com/RustCrypto/traits/pull/1821
- https://github.com/RustCrypto/traits/pull/1822
=> bump ff and group to pre-releases

ecdsa/src/der.rs, ecdsa/src/hazmat.rs, ecdsa/src/lib.rs, ecdsa/src/recovery.rs, ecdsa/src/signing.rs, ecdsa/src/verifying.rs
This name better gets the intent across
=> ecdsa: rename `DigestPrimitive` to `DigestAlgorithm`

Cargo.lock, dsa/Cargo.toml, ecdsa/src/hazmat.rs, ecdsa/src/recovery.rs
Uses the `Reduce` trait added in RustCrypto/traits#1949
=> ecdsa: use new `Reduce` trait

ecdsa/src/recovery.rs, ecdsa/src/verifying.rs
Infers types and makes these conversions less ugly
=> ecdsa: use `CtOption::into_option`

.github/workflows/dsa.yml, .github/workflows/ecdsa.yml, .github/workflows/ed25519.yml, .github/workflows/ed448.yml, .github/workflows/lms.yml, .github/workflows/ml-dsa.yml, .github/workflows/rfc6979.yml, .github/workflows/slh-dsa.yml, .github/workflows/workspace.yml
Same as https://github.com/RustCrypto/traits/pull/1948.
=> Only run CI on latest commit of PR branches.
